/**
 * Global integration test setup.
 *
 * Configured as a vitest `globalSetup` entry in `vitest.config.ts` —
 * runs ONCE before any test in `tests/integration/**` executes, in a
 * separate Node process. Returns an optional teardown function (no-op
 * here — the test process owns the PrismaClient for the run duration
 * and we don't need to clean anything up between suites; the next run
 * will wipe via this same file).
 *
 * Responsibilities:
 *   1. Push the Prisma schema to a throwaway SQLite file at `./test.db`
 *      (re-using the same path the CI workflow sets via DATABASE_URL).
 *      `--skip-generate` keeps the step fast — the client is already
 *      generated by the earlier `db:generate` step in CI (or locally by
 *      `bun install`, which runs a `postinstall` prisma generate).
 *
 *   2. Run `deleteMany({})` against EVERY table in the schema, in
 *      FK-safe order (children before parents). This guarantees each
 *      test run starts from a clean slate — no leakage of Users,
 *      ContactMessages, or any of the 41 wave-3 tables between test
 *      runs.
 *
 * The setup is idempotent: re-running `db push` on an existing schema
 * is a no-op (Prisma diff against itself), and `deleteMany({})` on an
 * empty table is a no-op.
 *
 * Why not use a transactional rollback per test?
 *   SQLite + Prisma's `$transaction([])` doesn't roll back DDL, and
 *   a per-test reset would slow the suite 5–10×. A single up-front
 *   sweep is fast (≈ 20 ms) and the tests themselves are small enough
 *   that cross-test pollution is manageable.
 */
import { execSync } from "node:child_process";
import { resolve } from "node:path";

const TEST_DB_PATH = "file:./test.db";

// ─── Env canonicalization (must run BEFORE importing src/**) ─────────
// globalSetup runs in its own process WITHOUT the worker's `setupFiles`,
// and importing src/lib/db.js evaluates the Zod-validated env loader
// (src/config/env.ts) which hard-exits when DATABASE_URL / JWT secrets
// are missing. Two rules:
//   1. DATABASE_URL is FORCED to the throwaway `file:./test.db` — an
//      ambient value (shell export, sandbox default) must never point
//      the suite at a real dev/prod database. This matches CI and the
//      `test:integration` script, which both set exactly this value.
//   2. JWT secrets get defaults when absent so a bare `bun run test`
//      works from a clean shell.
if (process.env.DATABASE_URL !== TEST_DB_PATH) {
  console.log(
    `[setup] Ignoring ambient DATABASE_URL="${process.env.DATABASE_URL ?? "<unset>"}" — tests always use ${TEST_DB_PATH}`,
  );
  process.env.DATABASE_URL = TEST_DB_PATH;
}
process.env.JWT_SECRET ??= "test-jwt-secret-32-chars-long";
process.env.JWT_REFRESH_SECRET ??= "test-refresh-secret-32-chars";

const { db } = await import("../../src/lib/db.js");

// `tests/integration/setup.ts` → backend root is two `..` segments up.
const BACKEND_ROOT = resolve(import.meta.dirname, "..", "..");

export default async function globalSetup(): Promise<() => Promise<void>> {
  // ─── Step 1 — push schema to test.db ──────────────────────────────────
  // We shell out rather than calling `prismaClient.$executeRaw` because
  // `prisma db push` is the supported way to (re)create the schema and
  // it handles migrations, drift detection, and SQLite file creation.
  //
  // The Prisma CLI loads `.env` automatically, but `process.env.DATABASE_URL`
  // takes precedence — and the `test:integration` script sets that env var
  // to `file:./test.db` before invoking vitest. So this `execSync` inherits
  // the right DATABASE_URL from the parent process.
  const prismaCmd = "bunx prisma db push --skip-generate --accept-data-loss";
  console.log("[setup] Running:", prismaCmd);
  console.log("[setup] cwd:", BACKEND_ROOT);
  console.log("[setup] DATABASE_URL:", process.env.DATABASE_URL ?? TEST_DB_PATH);
  execSync(prismaCmd, {
    cwd: BACKEND_ROOT,
    stdio: "inherit",
    env: {
      ...process.env,
      DATABASE_URL: TEST_DB_PATH,
    },
  });

  // ─── Step 2 — deleteMany on every table, FK-safe order ────────────────
  await wipeAll();

  return async function teardown() {
    // Close the Prisma connection pool — the globalSetup process is
    // about to exit, but the explicit disconnect keeps the SQLite file
    // handle released before tests read from it.
    try {
      await db.$disconnect();
    } catch {
      // Ignore — the OS will reclaim handles when the process exits.
    }
  };
}

// ─── FK-safe delete order ───────────────────────────────────────────────
//
// Children (tables that reference another via @relation) before parents.
// In our schema only `EffectFavorite` and `Collection` have enforced
// FKs (both → User, onDelete: Cascade), so they MUST be cleared before
// `User`. The remaining 43 tables have *Id columns that are logical
// (not DB-enforced) foreign keys — but we still order them
// children-before-parents defensively, in case FK constraints are added
// later.
//
// Order tiers (delete top-down):
//   Tier 1 — leaf children with enforced FKs: EffectFavorite, Collection
//   Tier 2 — dependent tables (have an *Id column, no FK):
//            PathProgress, ChallengeSubmission, CertificationAttempt,
//            AuditResult, AuditProject, CloudProject, Deployment,
//            FleetProject, StudioProject, PreviewBranch,
//            WorkspaceResource, Team, License, EnterpriseAuditLog,
//            GovernanceApproval, GovernancePolicy, TemplateReview,
//            Template, ComplianceScan, LiveMessage
//   Tier 3 — independent content/state tables (no FK refs at all):
//            LearningPath, Challenge, Certification, Organization,
//            Block, Blueprint, SpotlightItem, ObservatorySite,
//            LiveSession, GoodFirstIssue, RFC, Roadmap, Contributor,
//            BenchmarkResult, BundleResult, ProfilerResult,
//            TwinResult, Theme, OSDashboard, ComplianceStandard,
//            SearchIndex, ContactMessage
//   Tier 4 — parents: User (last, after EffectFavorite + Collection)
//
// Total: 47 tables (4 base models + 41 wave-3 models + Membership from
// issue #64 org-scoped authorization + ApiKey from issue #65 API-key
// auth). The schema's comment block "41 NEW MODELS (Wave 3)" refers to
// the wave-3 additions; this file clears all 47 so tests in auth.test.ts
// (User), contact.test.ts (ContactMessage), and api-keys.test.ts (ApiKey)
// start clean too.
const TABLES_IN_FK_SAFE_ORDER = [
  // ── Tier 1 — children with enforced FK to User ────────────────────
  "effectFavorite",
  "collection",
  // ── Tier 1.1 — org membership (enforced FKs to User + Organization) ─
  "membership",
  // ── Tier 1.2 — API keys (enforced FK to User; issue #65) ─────────
  "apiKey",
  // ── Tier 2 — dependent tables (logical *Id, no enforced FK) ──────
  "pathProgress",
  "challengeSubmission",
  "certificationAttempt",
  "auditResult",
  "complianceScan",
  "governanceApproval",
  "liveMessage",
  "templateReview",
  // ── Tier 2.5 — dependent but with nullable/optional FK columns ────
  "auditProject",
  "cloudProject",
  "deployment",
  "fleetProject",
  "studioProject",
  "previewBranch",
  "workspaceResource",
  "team",
  "license",
  "enterpriseAuditLog",
  "governancePolicy",
  "template",
  // ── Tier 3 — independent content/state tables ────────────────────
  "learningPath",
  "challenge",
  "certification",
  "organization",
  "block",
  "blueprint",
  "spotlightItem",
  "observatorySite",
  "liveSession",
  "goodFirstIssue",
  "rfc",
  "roadmap",
  "contributor",
  "benchmarkResult",
  "bundleResult",
  "profilerResult",
  "twinResult",
  "theme",
  "osDashboard",
  "complianceStandard",
  "searchIndex",
  "contactMessage",
  // ── Tier 4 — parent (after EffectFavorite + Collection cleared) ──
  "user",
] as const;

async function wipeAll(): Promise<void> {
  console.log(
    `[setup] Wiping ${TABLES_IN_FK_SAFE_ORDER.length} tables in FK-safe order…`,
  );
  for (const table of TABLES_IN_FK_SAFE_ORDER) {
    try {
      // `db as unknown as Record<string, { deleteMany: (args?: { where?: unknown }) => Promise<{ count: number }> }>`
      // is the typed escape hatch — Prisma's client is fully typed at
      // compile time but we want to iterate a runtime list of model
      // names without writing 45 separate `await db.X.deleteMany()`
      // calls. The cast is safe because every entry in the array above
      // is a real Prisma model delegate on `db`. The `args?` parameter
      // accepts an empty `{}` (delete-all) or a `where` clause.
      const model = (db as unknown as Record<
        string,
        { deleteMany: (args?: { where?: unknown }) => Promise<{ count: number }> }
      >)[table];
      if (!model || typeof model.deleteMany !== "function") {
        // Defensive — if Prisma ever renames a model delegate, we want
        // a clear message rather than a silent skip.
        console.warn(`[setup] No Prisma delegate for "${table}" — skipping`);
        continue;
      }
      const result = await model.deleteMany({});
      if (result.count > 0) {
        console.log(`[setup]   ${table}: deleted ${result.count} rows`);
      }
    } catch (err) {
      // Re-throw with context so a failed wipe doesn't look like a
      // passing test run.
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(`[setup] Failed to wipe table "${table}": ${msg}`);
    }
  }
  console.log("[setup] All tables wiped — test DB is clean.");
}
