/**
 * extract-critical-css.ts — Build dist/roycss-critical.css (top-50 effects).
 *
 * The full dist/roycss.css is 1.18 MB — too large to inline in <head>
 * without blocking first paint. RoyCSS already solves this two ways:
 *
 *   1. VirtualScrollGrid renders only 24 cards at a time (above-the-fold).
 *   2. DynamicEffectCSS injects effect CSS on demand via IntersectionObserver.
 *
 * But for the marketing site, both of those still need the BASE CSS
 * (reset, prefers-reduced-motion, sr-only) plus the CSS for the FIRST
 * ~50 effects that ship in the initial HTML payload. That's what this
 * script extracts.
 *
 * Output:
 *   dist/roycss-critical.css — BASE CSS + first 50 effect cssCodes
 *
 * Measured size target: ≤ 80 KB (vs 1.18 MB full bundle = 93% reduction).
 * Usage (Next.js):
 *
 *   <style dangerouslySetInnerHTML={{ __html: criticalCss }} />
 *   <link rel="preload" as="style" href="/roycss.css" />
 *
 * Or, with Next.js 16 App Router:
 *
 *   import criticalCss from "roycss/dist/roycss-critical.css?inline";
 *
 * Run:
 *   cd /home/z/my-project && bun run perf/optimize/extract-critical-css.ts
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CRITICAL_EFFECT_COUNT = 50;
const SIZE_BUDGET_BYTES = 80 * 1024; // 80 KB

interface EffectMeta { id: string; }

function readEffects(distDir: string): EffectMeta[] {
  const path = join(distDir, "effects.json");
  if (!existsSync(path)) throw new Error(`Missing: ${path}`);
  return JSON.parse(readFileSync(path, "utf-8"));
}

function readCssCodes(projectRoot: string): Map<string, string> {
  const srcLibDir = join(projectRoot, "src", "lib");
  const out = new Map<string, string>();
  for (let i = 1; i <= 34; i++) {
    const path = join(srcLibDir, `effects-batch-${i}.ts`);
    if (!existsSync(path)) continue;
    const src = readFileSync(path, "utf-8");
    let p = 0;
    while (p < src.length) {
      const idIdx = src.indexOf('id: "', p);
      if (idIdx < 0) break;
      const idStart = idIdx + 5;
      const idEnd = src.indexOf('"', idStart);
      if (idEnd < 0) break;
      const id = src.slice(idStart, idEnd);
      const cssIdx = src.indexOf("cssCode:", idEnd);
      const nextIdIdx = src.indexOf('id: "', idEnd);
      if (cssIdx < 0 || (nextIdIdx >= 0 && cssIdx > nextIdIdx)) {
        p = idEnd + 1; continue;
      }
      const tickStart = src.indexOf("`", cssIdx);
      if (tickStart < 0) break;
      let j = tickStart + 1;
      while (j < src.length) {
        if (src[j] === "\\" && j + 1 < src.length) { j += 2; continue; }
        if (src[j] === "`") break;
        j++;
      }
      out.set(id, src.slice(tickStart + 1, j));
      p = j + 1;
    }
  }
  return out;
}

function extractBaseCss(fullCss: string): string {
  // Everything from the banner comment through the end of the global
  // prefers-reduced-motion block — that's the BASE CSS that every page
  // needs regardless of which effects are visible.
  const prmEnd = fullCss.indexOf("}\n", fullCss.indexOf("prefers-reduced-motion"));
  if (prmEnd < 0) {
    throw new Error("Could not locate end of global prefers-reduced-motion block");
  }
  // Include the closing brace and trailing newline.
  return fullCss.slice(0, prmEnd + 2);
}

function main(): void {
  const projectRoot = join(__dirname, "..", "..");
  const distDir = join(projectRoot, "dist");
  const fullCssPath = join(distDir, "roycss.css");
  if (!existsSync(fullCssPath)) {
    throw new Error(`Missing: ${fullCssPath}. Run \`bun run build:package\` first.`);
  }
  const fullCss = readFileSync(fullCssPath, "utf-8");
  const effects = readEffects(distDir);
  const cssCodes = readCssCodes(projectRoot);
  const baseCss = extractBaseCss(fullCss);

  const top = effects.slice(0, CRITICAL_EFFECT_COUNT);
  const missing = top.filter((e) => !cssCodes.has(e.id));
  if (missing.length > 0) {
    throw new Error(`Missing cssCode for ${missing.length} top effects: ${missing.slice(0, 5).map((e) => e.id).join(", ")}`);
  }

  const effectCss = top
    .map((e) => cssCodes.get(e.id)!.trim())
    .join("\n\n");

  const header = `/*!
 * RoyCSS Critical CSS — auto-generated by perf/optimize/extract-critical-css.ts
 *
 * Contains:
 *   - Base CSS (reset, sr-only, prefers-reduced-motion global rule)
 *   - First ${CRITICAL_EFFECT_COUNT} effect cssCodes (above-the-fold set)
 *
 * Total effects in catalog: 1569
 * Critical effects bundled: ${CRITICAL_EFFECT_COUNT}
 * Full bundle:              roycss.css (load lazily after first paint)
 *
 * Source: dist/roycss.css + src/lib/effects-batch-*.ts
 * License: MIT
 */

`;

  const criticalCss = header + baseCss + "\n\n" + effectCss + "\n";
  const bytes = Buffer.byteLength(criticalCss, "utf-8");

  mkdirSync(distDir, { recursive: true });
  writeFileSync(join(distDir, "roycss-critical.css"), criticalCss, "utf-8");

  const pctOfFull = (bytes / fullCss.length * 100).toFixed(1);
  console.log("═══════════════════════════════════════════════════════════════");
  console.log("  RoyCSS Critical CSS extractor");
  console.log("═══════════════════════════════════════════════════════════════");
  console.log(`  Output:           dist/roycss-critical.css`);
  console.log(`  Effects bundled:  ${CRITICAL_EFFECT_COUNT} / 1569`);
  console.log(`  Size:             ${(bytes / 1024).toFixed(2)} KB (${bytes} bytes)`);
  console.log(`  % of full bundle: ${pctOfFull}%`);
  console.log(`  Budget:           ${(SIZE_BUDGET_BYTES / 1024).toFixed(0)} KB`);
  console.log(`  Status:           ${bytes <= SIZE_BUDGET_BYTES ? "✓ within budget" : "✗ OVER BUDGET"}`);
  console.log("═══════════════════════════════════════════════════════════════");
}

main();
