/**
 * RoyCSS Documentation Data Layer
 * -------------------------------
 * Lazy-loaded accessor for the build-time-generated `docs-content.json`.
 *
 * The JSON is generated by `scripts/build-docs.ts` and contains all 19
 * architecture markdown docs from `/docs/`. It is loaded on demand when
 * the user opens the docs overlay (see ADR 03-docs-site §2.2).
 *
 * Public API:
 *   - loadDocs()         → Promise<DocEntry[]>  (lazy, cached)
 *   - getDocs()          → DocEntry[] | null     (sync, returns cache)
 *   - getDocBySlug(s)    → DocEntry | null       (sync, returns cache)
 *   - categoryOrder      → string[]              (category display order)
 *   - categoryMeta       → Record<string, { label, icon }>
 *
 * See:
 *   - docs/adr/03-docs-site.md
 *   - docs/plans/03-docs-site.md
 */

import type { ComponentType } from "react";

/* ─── Types ──────────────────────────────────────────────────── */

export interface DocTocItem {
  /** Anchor ID, slugified. Matches the H2 id generated by rehype-slug at runtime. */
  id: string;
  /** Original heading text (e.g., "1. Goals"). */
  text: string;
  /** Heading level. Currently always 2 (we only index H2s). */
  level: number;
}

export interface DocEntry {
  /** Filename without extension, lowercased. e.g., "labs-26-reinvent-css". */
  slug: string;
  /** First H1 heading text. */
  title: string;
  /** Category ID, e.g., "architecture". */
  category: DocsCategoryId;
  /** Human-readable category label, e.g., "Architecture". */
  categoryLabel: string;
  /** First non-metadata paragraph after H1, truncated to 200 chars. */
  description: string;
  /** Full markdown source. */
  content: string;
  /** Auto-generated table of contents (H2 headings). */
  toc: DocTocItem[];
  /** Word count of the markdown source. */
  wordCount: number;
}

export type DocsCategoryId =
  | "architecture"
  | "product"
  | "quality"
  | "growth"
  | "tooling"
  | "uncategorized";

export interface DocsCategoryMeta {
  /** Human-readable label. */
  label: string;
  /** Short description shown under the category header. */
  description: string;
  /** Lucide icon component (resolved by the sidebar). */
  icon?: string;
}

/* ─── Category metadata ──────────────────────────────────────── */

export const categoryOrder: DocsCategoryId[] = [
  "architecture",
  "product",
  "quality",
  "growth",
  "tooling",
];

export const categoryMeta: Record<DocsCategoryId, DocsCategoryMeta> = {
  architecture: {
    label: "Architecture",
    description: "Foundational design decisions and language research.",
  },
  product: {
    label: "Product",
    description: "Vision, market positioning, and feature strategy.",
  },
  quality: {
    label: "Quality",
    description: "Performance, design review, and code-review labs.",
  },
  growth: {
    label: "Growth",
    description: "Scaling, boilerplate reduction, and adoption.",
  },
  tooling: {
    label: "Tooling",
    description: "Documentation and editor integration.",
  },
  uncategorized: {
    label: "Other",
    description: "Uncategorized documents.",
  },
};

/* ─── Lazy loader ────────────────────────────────────────────── */

let _docs: DocEntry[] | null = null;
let _loadPromise: Promise<DocEntry[]> | null = null;

/**
 * Load the docs JSON. Returns a cached promise so concurrent callers
 * share the same in-flight load.
 *
 * The dynamic import() lets webpack code-split the JSON into its own
 * chunk — it is NOT included in the main page bundle. See ADR §2.2.
 */
export function loadDocs(): Promise<DocEntry[]> {
  if (_docs) return Promise.resolve(_docs);
  if (_loadPromise) return _loadPromise;

  _loadPromise = import("./docs-content.json").then((mod) => {
    const data = (mod as unknown as { default: DocEntry[] }).default;
    if (!Array.isArray(data)) {
      throw new Error("docs-content.json: expected an array at .default");
    }
    _docs = data;
    _loadPromise = null;
    return data;
  });

  return _loadPromise;
}

/** Synchronous accessor for the cached docs. Returns null if not yet loaded. */
export function getDocs(): DocEntry[] | null {
  return _docs;
}

/** Look up a single doc by slug. Returns null if not found or not loaded. */
export function getDocBySlug(slug: string): DocEntry | null {
  if (!_docs) return null;
  return _docs.find((d) => d.slug === slug) ?? null;
}

/** Reset the cache (for tests). */
export function _resetDocsCache(): void {
  _docs = null;
  _loadPromise = null;
}
