#!/usr/bin/env bun
/**
 * RoyCSS CLI — Command-line tool for managing CSS effects
 *
 * Usage:
 *   roycss init                    Initialize RoyCSS in your project
 *   roycss add <effect-id>         Add an effect's CSS to your project
 *   roycss search <query>          Search for effects by name/tag/category
 *   roycss list [category]         List all effects or filter by category
 *   roycss categories              List all categories
 *   roycss info <effect-id>        Show details about a specific effect
 *   roycss doctor                  Check project health and get recommendations
 *   roycss version                 Show CLI version
 *   roycss help                    Show help
 *
 * Flags:
 *   --copy                         Copy CSS to clipboard instead of creating a file
 *   --tag <tag>                    Filter by tag (use with list/search)
 *   --framework <framework>        Show framework-specific usage (use with info)
 *   --json                         Output as JSON (use with search/list)
 */

import { effects, categoryMeta, categoryOrder } from "../lib/roycss-effects";
import { writeFileSync, readFileSync, existsSync, mkdirSync, readdirSync } from "fs";
import { join, dirname } from "path";

// ═══════════════════════════════════════════════════════════════
// Terminal colors
// ═══════════════════════════════════════════════════════════════

const c = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  green: "\x1b[32m",
  cyan: "\x1b[36m",
  yellow: "\x1b[33m",
  red: "\x1b[31m",
  magenta: "\x1b[35m",
  gray: "\x1b[90m",
  bg: "\x1b[48;5;22m",
};

function log(msg: string) { console.log(msg); }
function success(msg: string) { console.log(`${c.green}✓${c.reset} ${msg}`); }
function error(msg: string) { console.error(`${c.red}✗${c.reset} ${msg}`); }
function info(msg: string) { console.log(`${c.cyan}ℹ${c.reset} ${msg}`); }
function warn(msg: string) { console.log(`${c.yellow}⚠${c.reset} ${msg}`); }

const VERSION = "1.0.0";

// ═══════════════════════════════════════════════════════════════
// Helper: parse flags from args
// ═══════════════════════════════════════════════════════════════

function parseFlags(args: string[]): { positional: string[]; flags: Record<string, string | boolean> } {
  const positional: string[] = [];
  const flags: Record<string, string | boolean> = {};

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg.startsWith("--")) {
      const key = arg.slice(2);
      const next = args[i + 1];
      if (next && !next.startsWith("--")) {
        flags[key] = next;
        i++;
      } else {
        flags[key] = true;
      }
    } else {
      positional.push(arg);
    }
  }

  return { positional, flags };
}

// ═══════════════════════════════════════════════════════════════
// Helper: copy to clipboard
// ═══════════════════════════════════════════════════════════════

async function copyToClipboard(text: string): Promise<boolean> {
  try {
    const proc = Bun.spawn(["xclip", "-selection", "clipboard"], {
      stdin: "pipe",
      stdout: "null",
      stderr: "null",
    });
    proc.stdin.write(text);
    proc.stdin.end();
    await proc.exited;
    return true;
  } catch {
    try {
      const proc = Bun.spawn(["pbcopy"], {
        stdin: "pipe",
        stdout: "null",
        stderr: "null",
      });
      proc.stdin.write(text);
      proc.stdin.end();
      await proc.exited;
      return true;
    } catch {
      return false;
    }
  }
}

// ═══════════════════════════════════════════════════════════════
// Commands
// ═══════════════════════════════════════════════════════════════

function cmdInit(flags: Record<string, string | boolean>) {
  const framework = (flags.framework as string) || "vanilla";

  log(`${c.bold}${c.cyan}RoyCSS${c.reset} ${c.gray}v${VERSION}${c.reset}`);
  log(`${c.dim}Initializing RoyCSS in your project...${c.reset}\n`);

  // Check if CSS file already exists
  const cssPath = "roycss.css";
  if (existsSync(cssPath) && !flags.force) {
    info(`roycss.css already exists. Use ${c.cyan}--force${c.reset} to overwrite.`);
  } else {
    // Generate the full CSS file with all effects
    const allCSS = effects.map((e) => e.cssCode).join("\n\n");
    const header = `/* RoyCSS — ${effects.length}+ CSS Effects\n * Generated by: roycss init\n * Framework: ${framework}\n * Learn more: https://github.com/Roy-Wanyoike/roycss\n */\n\n`;
    writeFileSync(cssPath, header + allCSS);
    success(`Created ${c.bold}roycss.css${c.reset} with ${effects.length}+ effects`);
  }

  // Framework-specific instructions
  const frameworkInstructions: Record<string, string[]> = {
    vanilla: [
      `Import the CSS:`,
      `  ${c.cyan}<link rel="stylesheet" href="roycss.css" />${c.reset}`,
    ],
    react: [
      `Import in your entry file (src/main.tsx):`,
      `  ${c.cyan}import "./roycss.css";${c.reset}`,
    ],
    vue: [
      `Import in src/main.ts:`,
      `  ${c.cyan}import "./roycss.css";${c.reset}`,
    ],
    angular: [
      `Add to angular.json styles array:`,
      `  ${c.cyan}"roycss.css"${c.reset}`,
    ],
    svelte: [
      `Import in src/main.ts:`,
      `  ${c.cyan}import "./roycss.css";${c.reset}`,
    ],
    nextjs: [
      `Import in src/app/layout.tsx:`,
      `  ${c.cyan}import "./roycss.css";${c.reset}`,
    ],
  };

  log(`\n${c.bold}Next steps (${framework}):${c.reset}`);
  (frameworkInstructions[framework] || frameworkInstructions.vanilla).forEach((line) =>
    log(`  ${line}`),
  );

  log(`\n  ${c.gray}Use any effect:${c.reset}`);
  log(`  ${c.cyan}<div class="roycss-pulse-glow">Hello</div>${c.reset}`);

  log(`\n  ${c.gray}Search for effects:${c.reset}`);
  log(`  ${c.cyan}roycss search glow${c.reset}`);

  log(`\n  ${c.gray}Add a specific effect only:${c.reset}`);
  log(`  ${c.cyan}roycss add pulse-glow${c.reset}`);

  log(`\n${c.green}Done!${c.reset} Visit ${c.cyan}https://github.com/Roy-Wanyoike/roycss${c.reset} for docs.`);
}

async function cmdAdd(effectId: string, flags: Record<string, string | boolean>) {
  const effect = effects.find((e) => e.id === effectId);
  if (!effect) {
    // Fuzzy match
    const fuzzy = effects.filter(
      (e) => e.id.includes(effectId) || effectId.includes(e.id),
    );
    error(`Effect "${effectId}" not found.`);
    if (fuzzy.length > 0) {
      log(`\n  ${c.dim}Did you mean?${c.reset}`);
      fuzzy.slice(0, 5).forEach((e) => {
        log(`    ${c.cyan}roycss-${e.id}${c.reset} ${c.gray}—${c.reset} ${e.name}`);
      });
    }
    process.exit(1);
  }

  // --copy flag: copy to clipboard
  if (flags.copy) {
    const copied = await copyToClipboard(effect.cssCode);
    if (copied) {
      success(`Copied ${c.bold}roycss-${effect.id}${c.reset} CSS to clipboard`);
    } else {
      warn(`Could not copy to clipboard. Outputting to stdout:\n`);
      log(effect.cssCode);
    }
    return;
  }

  // Write just this effect's CSS
  const fileName = `roycss-${effectId}.css`;
  writeFileSync(fileName, effect.cssCode);
  success(`Created ${c.bold}${fileName}${c.reset}`);

  log(`\n${c.dim}Usage:${c.reset}`);
  log(`  ${c.gray}// Import in your CSS${c.reset}`);
  log(`  ${c.cyan}@import "roycss-${effectId}.css";${c.reset}`);
  log(`\n  ${c.gray}// HTML${c.reset}`);
  log(`  ${c.cyan}<div class="roycss-${effectId}">${effect.previewText || "Content"}</div>${c.reset}`);

  if (effect.childCount) {
    log(`\n  ${c.yellow}⚠ This effect requires ${effect.childCount} child <span> elements:${c.reset}`);
    log(`  ${c.cyan}<div class="roycss-${effectId}">${c.reset}`);
    for (let i = 0; i < effect.childCount; i++) {
      log(`    ${c.cyan}<span></span>${c.reset}`);
    }
    log(`  ${c.cyan}</div>${c.reset}`);
  }
}

function cmdSearch(query: string, flags: Record<string, string | boolean>) {
  const q = query.toLowerCase();
  let results = effects.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.description.toLowerCase().includes(q) ||
      e.tags.some((t) => t.toLowerCase().includes(q)) ||
      e.category.includes(q) ||
      e.id.includes(q),
  );

  // Filter by tag
  if (flags.tag) {
    const tag = (flags.tag as string).toLowerCase();
    results = results.filter((e) => e.tags.some((t) => t.toLowerCase().includes(tag)));
  }

  // JSON output
  if (flags.json) {
    console.log(
      JSON.stringify(
        {
          query,
          tag: flags.tag || null,
          totalFound: results.length,
          effects: results.slice(0, 50).map((e) => ({
            id: e.id,
            name: e.name,
            category: categoryMeta[e.category].label,
            description: e.description,
            tags: e.tags,
          })),
        },
        null,
        2,
      ),
    );
    return;
  }

  if (results.length === 0) {
    log(`${c.gray}No effects found for "${query}".${c.reset}`);
    log(`${c.dim}Try: ${categoryOrder.slice(0, 5).join(", ")}...${c.reset}`);
    return;
  }

  log(`${c.bold}Found ${results.length} effect${results.length === 1 ? "" : "s"} for "${query}"${flags.tag ? ` tagged "${flags.tag}"` : ""}:${c.reset}\n`);

  results.slice(0, 20).forEach((e) => {
    const catLabel = categoryMeta[e.category].label;
    log(`  ${c.cyan}roycss-${e.id}${c.reset} ${c.gray}—${c.reset} ${e.name} ${c.dim}(${catLabel})${c.reset}`);
  });

  if (results.length > 20) {
    log(`\n  ${c.dim}...and ${results.length - 20} more. Use ${c.reset}${c.cyan}--json${c.reset}${c.dim} for full results.${c.reset}`);
  }

  log(`\n${c.dim}Add an effect: ${c.reset}${c.cyan}roycss add <effect-id>${c.reset}`);
}

function cmdList(category: string | undefined, flags: Record<string, string | boolean>) {
  // JSON output
  if (flags.json) {
    if (category) {
      const cat = categoryOrder.find(
        (c) => c === category || categoryMeta[c].label.toLowerCase() === category.toLowerCase(),
      );
      if (!cat) {
        error(`Category "${category}" not found.`);
        process.exit(1);
      }
      const items = effects.filter((e) => e.category === cat);
      console.log(JSON.stringify({ category: cat, count: items.length, effects: items.map((e) => ({ id: e.id, name: e.name, description: e.description })) }, null, 2));
    } else {
      console.log(
        JSON.stringify(
          {
            totalEffects: effects.length,
            categories: categoryOrder.map((cat) => ({
              id: cat,
              label: categoryMeta[cat].label,
              count: effects.filter((e) => e.category === cat).length,
            })),
          },
          null,
          2,
        ),
      );
    }
    return;
  }

  if (category) {
    const cat = categoryOrder.find(
      (c) => c === category || categoryMeta[c].label.toLowerCase() === category.toLowerCase(),
    );
    if (!cat) {
      error(`Category "${category}" not found.`);
      log(`  Available: ${categoryOrder.join(", ")}`);
      process.exit(1);
    }
    const items = effects.filter((e) => e.category === cat);
    log(`${c.bold}${categoryMeta[cat].label} (${items.length}):${c.reset}\n`);
    items.forEach((e) => {
      log(`  ${c.cyan}roycss-${e.id}${c.reset} ${c.gray}—${c.reset} ${e.description.substring(0, 60)}`);
    });
  } else {
    log(`${c.bold}All ${effects.length}+ RoyCSS effects across ${categoryOrder.length} categories:${c.reset}\n`);
    for (const cat of categoryOrder) {
      const items = effects.filter((e) => e.category === cat);
      log(`  ${c.magenta}${categoryMeta[cat].label}${c.reset} ${c.dim}(${items.length})${c.reset}`);
      items.slice(0, 3).forEach((e) => {
        log(`    ${c.cyan}roycss-${e.id}${c.reset} ${c.gray}—${c.reset} ${e.name}`);
      });
      if (items.length > 3) {
        log(`    ${c.dim}...and ${items.length - 3} more${c.reset}`);
      }
      log("");
    }
  }
}

function cmdCategories() {
  log(`${c.bold}RoyCSS Categories (${categoryOrder.length}):${c.reset}\n`);
  for (const cat of categoryOrder) {
    const count = effects.filter((e) => e.category === cat).length;
    log(`  ${c.magenta}${categoryMeta[cat].label}${c.reset} ${c.dim}(${count})${c.reset} — ${categoryMeta[cat].description}`);
  }
  log(`\n${c.dim}Total: ${effects.length}+ effects${c.reset}`);
  log(`${c.dim}Browse: ${c.reset}${c.cyan}roycss list <category>${c.reset}`);
}

function cmdInfo(effectId: string, flags: Record<string, string | boolean>) {
  const effect = effects.find((e) => e.id === effectId);
  if (!effect) {
    // Fuzzy match
    const fuzzy = effects.filter(
      (e) => e.id.includes(effectId) || effectId.includes(e.id),
    );
    error(`Effect "${effectId}" not found.`);
    if (fuzzy.length > 0) {
      log(`\n  ${c.dim}Did you mean?${c.reset}`);
      fuzzy.slice(0, 5).forEach((e) => {
        log(`    ${c.cyan}roycss-${e.id}${c.reset} ${c.gray}—${c.reset} ${e.name}`);
      });
    }
    process.exit(1);
  }

  log(`${c.bold}${c.cyan}${effect.name}${c.reset} ${c.dim}(roycss-${effect.id})${c.reset}`);
  log(`\n${c.bold}Description:${c.reset} ${effect.description}`);
  log(`${c.bold}Category:${c.reset} ${categoryMeta[effect.category].label}`);
  log(`${c.bold}Tags:${c.reset} ${effect.tags.join(", ")}`);
  log(`${c.bold}Preview Type:${c.reset} ${effect.previewType}`);
  if (effect.childCount) {
    log(`${c.bold}Child Elements:${c.reset} ${effect.childCount} <span> elements required`);
  }

  // Framework usage
  if (flags.framework) {
    const fw = (flags.framework as string).toLowerCase();
    const cls = `roycss-${effect.id}`;
    const examples: Record<string, string> = {
      react: `<button className="${cls}" type="button">${effect.name}</button>`,
      vue: `<button class="${cls}" type="button">${effect.name}</button>`,
      svelte: `<button class="${cls}">${effect.name}</button>`,
      angular: `<button class="${cls}" type="button">${effect.name}</button>`,
      vanilla: `<button class="${cls}">${effect.name}</button>`,
      nextjs: `<button className="${cls}" type="button">${effect.name}</button>`,
    };
    log(`\n${c.bold}${fw} usage:${c.reset}`);
    log(`  ${c.cyan}${examples[fw] || examples.vanilla}${c.reset}`);
  }

  log(`\n${c.bold}CSS:${c.reset}`);
  log(`${c.gray}${effect.cssCode}${c.reset}`);
  log(`\n${c.dim}Add to project: ${c.reset}${c.cyan}roycss add ${effect.id}${c.reset}`);
  log(`${c.dim}Copy to clipboard: ${c.reset}${c.cyan}roycss add ${effect.id} --copy${c.reset}`);
}

function cmdDoctor() {
  log(`${c.bold}${c.cyan}RoyCSS Doctor${c.reset} ${c.gray}v${VERSION}${c.reset}`);
  log(`${c.dim}Checking project health...${c.reset}\n`);

  let issues = 0;

  // Check 1: roycss.css exists?
  if (existsSync("roycss.css")) {
    success(`${c.bold}roycss.css${c.reset} found`);
    // Check size
    const stat = readFileSync("roycss.css");
    if (stat.length > 1000) {
      success(`CSS file size: ${(stat.length / 1024).toFixed(1)}KB`);
    } else {
      warn(`CSS file seems small (${stat.length} bytes) — may be incomplete`);
      issues++;
    }
  } else {
    // Check if roycss is installed as a package
    if (existsSync("node_modules/roycss")) {
      success(`${c.bold}roycss${c.reset} package found in node_modules`);
    } else {
      warn(`${c.bold}roycss.css${c.reset} not found — run ${c.cyan}roycss init${c.reset} to create it`);
      issues++;
    }
  }

  // Check 2: package.json has roycss?
  if (existsSync("package.json")) {
    try {
      const pkg = JSON.parse(readFileSync("package.json", "utf-8"));
      const deps = { ...pkg.dependencies, ...pkg.devDependencies };
      if (deps.roycss) {
        success(`${c.bold}roycss${c.reset} found in package.json (${deps.roycss})`);
      } else {
        info(`${c.bold}roycss${c.reset} not in package.json — using CDN or local file`);
      }
    } catch {
      // ignore
    }
  }

  // Check 3: CSS import in common entry points
  const entryPoints = [
    "src/main.tsx",
    "src/main.ts",
    "src/index.ts",
    "src/app/layout.tsx",
    "src/app/globals.css",
    "index.html",
    "angular.json",
  ];
  let foundImport = false;
  for (const ep of entryPoints) {
    if (existsSync(ep)) {
      const content = readFileSync(ep, "utf-8");
      if (content.includes("roycss")) {
        success(`RoyCSS import found in ${c.bold}${ep}${c.reset}`);
        foundImport = true;
        break;
      }
    }
  }
  if (!foundImport && existsSync("roycss.css")) {
    warn(`No RoyCSS import found in common entry points`);
    log(`  ${c.dim}Add to your entry file:${c.reset}`);
    log(`  ${c.cyan}import "./roycss.css";${c.reset}`);
    issues++;
  }

  // Check 4: roycss classes in use?
  let classesFound = 0;
  const srcDirs = ["src", "app", "pages", "components"];
  function scanDir(dir: string) {
    try {
      const entries = readdirSync(dir, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = join(dir, entry.name);
        if (entry.isDirectory() && !entry.name.startsWith(".") && entry.name !== "node_modules") {
          scanDir(fullPath);
        } else if (entry.name.endsWith(".tsx") || entry.name.endsWith(".jsx") || entry.name.endsWith(".vue") || entry.name.endsWith(".svelte") || entry.name.endsWith(".html")) {
          try {
            const content = readFileSync(fullPath, "utf-8");
            const matches = content.match(/roycss-[a-z0-9-]+/g);
            if (matches) classesFound += matches.length;
          } catch {
            // ignore
          }
        }
      }
    } catch {
      // ignore
    }
  }
  for (const dir of srcDirs) {
    if (existsSync(dir)) scanDir(dir);
  }
  if (classesFound > 0) {
    success(`${c.bold}${classesFound}${c.reset} RoyCSS class usage${classesFound === 1 ? "" : "es"} found in source files`);
  } else {
    info(`No RoyCSS classes found in source files — start using them!`);
  }

  // Summary
  log(`\n${c.bold}Summary:${c.reset}`);
  if (issues === 0) {
    success(`${c.green}All checks passed!${c.reset} Your project is healthy.`);
  } else {
    warn(`${issues} issue${issues === 1 ? "" : "s"} found. See above for recommendations.`);
  }

  log(`\n${c.dim}RoyCSS ${effects.length}+ effects available | ${categoryOrder.length} categories${c.reset}`);
  log(`${c.dim}Docs: https://github.com/Roy-Wanyoike/roycss${c.reset}`);
}

function cmdVersion() {
  log(`RoyCSS CLI v${VERSION}`);
  log(`${c.dim}${effects.length}+ effects across ${categoryOrder.length} categories${c.reset}`);
}

function cmdHelp() {
  log(`${c.bold}${c.cyan}RoyCSS CLI${c.reset} ${c.gray}v${VERSION}${c.reset}`);
  log(`${c.dim}${effects.length}+ production-ready CSS effects across ${categoryOrder.length} categories${c.reset}\n`);

  log(`${c.bold}Commands:${c.reset}`);
  log(`  ${c.cyan}init${c.reset}                      Initialize RoyCSS in your project`);
  log(`  ${c.cyan}add${c.reset} <effect-id>           Add a specific effect's CSS file`);
  log(`  ${c.cyan}search${c.reset} <query>            Search effects by name, tag, or category`);
  log(`  ${c.cyan}list${c.reset} [category]           List all effects or filter by category`);
  log(`  ${c.cyan}categories${c.reset}                List all effect categories`);
  log(`  ${c.cyan}info${c.reset} <effect-id>          Show details about a specific effect`);
  log(`  ${c.cyan}doctor${c.reset}                    Check project health and get recommendations`);
  log(`  ${c.cyan}version${c.reset}                   Show CLI version`);
  log(`  ${c.cyan}help${c.reset}                      Show this help message`);

  log(`\n${c.bold}Flags:${c.reset}`);
  log(`  ${c.cyan}--copy${c.reset}                    Copy CSS to clipboard (use with ${c.dim}add${c.reset})`);
  log(`  ${c.cyan}--tag${c.reset} <tag>               Filter by tag (use with ${c.dim}search/list${c.reset})`);
  log(`  ${c.cyan}--framework${c.reset} <name>        Show framework usage (use with ${c.dim}info/init${c.reset})`);
  log(`  ${c.cyan}--json${c.reset}                    Output as JSON (use with ${c.dim}search/list${c.reset})`);
  log(`  ${c.cyan}--force${c.reset}                   Overwrite existing files (use with ${c.dim}init${c.reset})`);

  log(`\n${c.bold}Examples:${c.reset}`);
  log(`  ${c.gray}roycss init${c.reset}`);
  log(`  ${c.gray}roycss init --framework react${c.reset}`);
  log(`  ${c.gray}roycss add pulse-glow${c.reset}`);
  log(`  ${c.gray}roycss add pulse-glow --copy${c.reset}`);
  log(`  ${c.gray}roycss search "glass card"${c.reset}`);
  log(`  ${c.gray}roycss search loading --tag spinner${c.reset}`);
  log(`  ${c.gray}roycss list animations${c.reset}`);
  log(`  ${c.gray}roycss info btn-shine-sweep --framework react${c.reset}`);
  log(`  ${c.gray}roycss doctor${c.reset}`);
  log(`  ${c.gray}roycss list --json${c.reset}`);

  log(`\n${c.dim}Learn more: https://github.com/Roy-Wanyoike/roycss${c.reset}`);
}

// ═══════════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════════

const [command, ...rawArgs] = process.argv.slice(2);
const { positional, flags } = parseFlags(rawArgs);

switch (command) {
  case "init":
    cmdInit(flags);
    break;
  case "add":
    if (!positional[0]) {
      error("Usage: roycss add <effect-id> [--copy]");
      process.exit(1);
    }
    cmdAdd(positional[0], flags);
    break;
  case "search":
    if (!positional[0]) {
      error("Usage: roycss search <query> [--tag <tag>] [--json]");
      process.exit(1);
    }
    cmdSearch(positional.join(" "), flags);
    break;
  case "list":
    cmdList(positional[0], flags);
    break;
  case "categories":
    cmdCategories();
    break;
  case "info":
    if (!positional[0]) {
      error("Usage: roycss info <effect-id> [--framework <name>]");
      process.exit(1);
    }
    cmdInfo(positional[0], flags);
    break;
  case "doctor":
    cmdDoctor();
    break;
  case "version":
  case "--version":
  case "-v":
    cmdVersion();
    break;
  case "help":
  case "--help":
  case "-h":
  case undefined:
    cmdHelp();
    break;
  default:
    error(`Unknown command: ${command}`);
    log("");
    cmdHelp();
    process.exit(1);
}
