#!/usr/bin/env bun
/**
 * RoyCSS CLI — Command-line tool for managing CSS effects
 *
 * Usage:
 *   roycss init                    Initialize RoyCSS in your project
 *   roycss add <effect-id>         Add an effect's CSS to your project
 *   roycss search <query>          Search for effects by name/tag
 *   roycss list [category]         List all effects or by category
 *   roycss categories              List all categories
 *   roycss info <effect-id>        Show details about a specific effect
 */

import { effects, categoryMeta, categoryOrder } from "../lib/roycss-effects";
import { writeFileSync, readFileSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";

// ─── Colors for terminal output ──────────────────────────────
const c = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  green: "\x1b[32m",
  cyan: "\x1b[36m",
  yellow: "\x1b[33m",
  red: "\x1b[31m",
  magenta: "\x1b[35m",
  gray: "\x1b[90m",
};

function log(msg: string) { console.log(msg); }
function success(msg: string) { console.log(`${c.green}✓${c.reset} ${msg}`); }
function error(msg: string) { console.error(`${c.red}✗${c.reset} ${msg}`); }
function info(msg: string) { console.log(`${c.cyan}ℹ${c.reset} ${msg}`); }

// ─── Commands ────────────────────────────────────────────────

function cmdInit() {
  log(`${c.bold}${c.cyan}RoyCSS${c.reset} ${c.gray}v1.0.0${c.reset}`);
  log(`${c.dim}Initializing RoyCSS in your project...${c.reset}\n`);

  // Check if CSS file already exists
  const cssPath = "roycss.css";
  if (existsSync(cssPath)) {
    info(`roycss.css already exists. Skipping creation.`);
  } else {
    // Generate the full CSS file with all effects
    const allCSS = effects.map(e => e.cssCode).join("\n\n");
    const header = `/* RoyCSS — ${effects.length} CSS Effects\n * Generated by: roycss init\n * Learn more: https://roycss.dev\n */\n\n`;
    writeFileSync(cssPath, header + allCSS);
    success(`Created ${c.bold}roycss.css${c.reset} with ${effects.length} effects`);
  }

  log(`\n${c.bold}Next steps:${c.reset}`);
  log(`  1. Import the CSS in your app:`);
  log(`     ${c.gray}// In your root CSS or layout${c.reset}`);
  log(`     ${c.cyan}@import "roycss.css";${c.reset}`);
  log(`\n  2. Use any effect by adding its class:`);
  log(`     ${c.gray}<div class="roycss-pulse-glow">Hello</div>${c.reset}`);
  log(`\n  3. Search for effects:`);
  log(`     ${c.cyan}roycss search glow${c.reset}`);
  log(`\n  4. Add a specific effect's CSS only:`);
  log(`     ${c.cyan}roycss add pulse-glow${c.reset}`);
  log(`\n${c.green}Done!${c.reset} Visit ${c.cyan}https://roycss.dev${c.reset} for live demos.`);
}

function cmdAdd(effectId: string) {
  const effect = effects.find(e => e.id === effectId);
  if (!effect) {
    error(`Effect "${effectId}" not found.`);
    log(`  Run ${c.cyan}roycss search ${effectId}${c.reset} to find similar effects.`);
    process.exit(1);
  }

  // Write just this effect's CSS
  const fileName = `roycss-${effectId}.css`;
  writeFileSync(fileName, effect.cssCode);
  success(`Created ${c.bold}${fileName}${c.reset}`);
  log(`\n${c.dim}Usage:${c.reset}`);
  log(`  ${c.gray}// Import in your CSS${c.reset}`);
  log(`  ${c.cyan}@import "roycss-${effectId}.css";${c.reset}`);
  log(`\n  ${c.gray}// HTML${c.reset}`);
  log(`  ${c.cyan}<div class="roycss-${effectId}">${effect.previewText || "Content"}</div>${c.reset}`);
  
  if (effect.childCount) {
    log(`\n  ${c.yellow}⚠ This effect requires ${effect.childCount} child <span> elements:${c.reset}`);
    log(`  ${c.cyan}<div class="roycss-${effectId}">${c.reset}`);
    for (let i = 0; i < effect.childCount; i++) {
      log(`    ${c.cyan}<span></span>${c.reset}`);
    }
    log(`  ${c.cyan}</div>${c.reset}`);
  }
}

function cmdSearch(query: string) {
  const q = query.toLowerCase();
  const results = effects.filter(e =>
    e.name.toLowerCase().includes(q) ||
    e.description.toLowerCase().includes(q) ||
    e.tags.some(t => t.toLowerCase().includes(q)) ||
    e.category.includes(q)
  );

  if (results.length === 0) {
    log(`${c.gray}No effects found for "${query}".${c.reset}`);
    log(`${c.dim}Try: ${categoryOrder.map(c => categoryMeta[c].label.toLowerCase()).slice(0, 5).join(", ")}...${c.reset}`);
    return;
  }

  log(`${c.bold}Found ${results.length} effect${results.length === 1 ? "" : "s"} for "${query}":${c.reset}\n`);
  
  results.slice(0, 20).forEach(e => {
    const catLabel = categoryMeta[e.category].label;
    log(`  ${c.cyan}roycss-${e.id}${c.reset} ${c.gray}—${c.reset} ${e.name} ${c.dim}(${catLabel})${c.reset}`);
  });
  
  if (results.length > 20) {
    log(`\n  ${c.dim}...and ${results.length - 20} more. Refine your search.${c.reset}`);
  }
  
  log(`\n${c.dim}Add an effect: ${c.reset}${c.cyan}roycss add <effect-id>${c.reset}`);
}

function cmdList(category?: string) {
  if (category) {
    const cat = categoryOrder.find(c => c === category || categoryMeta[c].label.toLowerCase() === category.toLowerCase());
    if (!cat) {
      error(`Category "${category}" not found.`);
      log(`  Available: ${categoryOrder.join(", ")}`);
      process.exit(1);
    }
    const items = effects.filter(e => e.category === cat);
    log(`${c.bold}${categoryMeta[cat].label} (${items.length}):${c.reset}\n`);
    items.forEach(e => {
      log(`  ${c.cyan}roycss-${e.id}${c.reset} ${c.gray}—${c.reset} ${e.description.substring(0, 60)}`);
    });
  } else {
    log(`${c.bold}All ${effects.length} RoyCSS effects:${c.reset}\n`);
    for (const cat of categoryOrder) {
      const items = effects.filter(e => e.category === cat);
      log(`  ${c.magenta}${categoryMeta[cat].label}${c.reset} ${c.dim}(${items.length})${c.reset}`);
      items.slice(0, 3).forEach(e => {
        log(`    ${c.cyan}roycss-${e.id}${c.reset} ${c.gray}—${c.reset} ${e.name}`);
      });
      if (items.length > 3) {
        log(`    ${c.dim}...and ${items.length - 3} more${c.reset}`);
      }
      log("");
    }
  }
}

function cmdCategories() {
  log(`${c.bold}RoyCSS Categories (${categoryOrder.length}):${c.reset}\n`);
  for (const cat of categoryOrder) {
    const count = effects.filter(e => e.category === cat).length;
    log(`  ${c.magenta}${categoryMeta[cat].label}${c.reset} ${c.dim}(${count})${c.reset} — ${categoryMeta[cat].description}`);
  }
}

function cmdInfo(effectId: string) {
  const effect = effects.find(e => e.id === effectId);
  if (!effect) {
    error(`Effect "${effectId}" not found.`);
    process.exit(1);
  }

  log(`${c.bold}${c.cyan}${effect.name}${c.reset} ${c.dim}(roycss-${effect.id})${c.reset}`);
  log(`\n${c.bold}Description:${c.reset} ${effect.description}`);
  log(`${c.bold}Category:${c.reset} ${categoryMeta[effect.category].label}`);
  log(`${c.bold}Tags:${c.reset} ${effect.tags.join(", ")}`);
  log(`${c.bold}Preview Type:${c.reset} ${effect.previewType}`);
  if (effect.childCount) {
    log(`${c.bold}Child Elements:${c.reset} ${effect.childCount} <span> elements required`);
  }
  log(`\n${c.bold}CSS:${c.reset}`);
  log(`${c.gray}${effect.cssCode}${c.reset}`);
  log(`\n${c.dim}Add to project: ${c.reset}${c.cyan}roycss add ${effect.id}${c.reset}`);
}

function cmdHelp() {
  log(`${c.bold}${c.cyan}RoyCSS CLI${c.reset} ${c.gray}v1.0.0${c.reset}`);
  log(`${c.dim}700+ production-ready CSS effects${c.reset}\n`);
  log(`${c.bold}Commands:${c.reset}`);
  log(`  ${c.cyan}init${c.reset}                    Initialize RoyCSS in your project`);
  log(`  ${c.cyan}add${c.reset} <effect-id>         Add a specific effect's CSS file`);
  log(`  ${c.cyan}search${c.reset} <query>          Search effects by name, tag, or category`);
  log(`  ${c.cyan}list${c.reset} [category]         List all effects or filter by category`);
  log(`  ${c.cyan}categories${c.reset}              List all effect categories`);
  log(`  ${c.cyan}info${c.reset} <effect-id>        Show details about a specific effect`);
  log(`  ${c.cyan}help${c.reset}                    Show this help message`);
  log(`\n${c.bold}Examples:${c.reset}`);
  log(`  ${c.gray}roycss init${c.reset}`);
  log(`  ${c.gray}roycss add pulse-glow${c.reset}`);
  log(`  ${c.gray}roycss search loading${c.reset}`);
  log(`  ${c.gray}roycss list animations${c.reset}`);
  log(`\n${c.dim}Learn more: https://roycss.dev${c.reset}`);
}

// ─── Main ────────────────────────────────────────────────────

const [command, ...args] = process.argv.slice(2);

switch (command) {
  case "init":
    cmdInit();
    break;
  case "add":
    if (!args[0]) { error("Usage: roycss add <effect-id>"); process.exit(1); }
    cmdAdd(args[0]);
    break;
  case "search":
    if (!args[0]) { error("Usage: roycss search <query>"); process.exit(1); }
    cmdSearch(args.join(" "));
    break;
  case "list":
    cmdList(args[0]);
    break;
  case "categories":
    cmdCategories();
    break;
  case "info":
    if (!args[0]) { error("Usage: roycss info <effect-id>"); process.exit(1); }
    cmdInfo(args[0]);
    break;
  case "help":
  case "--help":
  case "-h":
    cmdHelp();
    break;
  default:
    if (command) {
      error(`Unknown command: ${command}`);
      log("");
    }
    cmdHelp();
    process.exit(command ? 1 : 0);
}
