/**
 * security/csp.ts
 *
 * Generates two Content-Security-Policy strings:
 *
 *   1. `results/csp.txt` — Development CSP
 *      Next.js dev mode (HMR, React Refresh, Turbopack) injects inline
 *      scripts without nonces. The dev CSP allows `'unsafe-inline'` for
 *      scripts to avoid breaking HMR. Still forbids external sources.
 *
 *   2. `results/csp-production.txt` — Production CSP (with nonce placeholder)
 *      Uses per-request nonces generated by `src/middleware.ts` via
 *      `crypto.randomBytes(16).toString("base64")`. The string below
 *      uses the literal placeholder `'nonce-{{NONCE}}'` which the
 *      middleware replaces with the actual nonce before sending the
 *      response header.
 *
 *      The production policy also enables `'strict-dynamic'`, which
 *      allows nonce-bearing scripts to load their own script
 *      dependencies without listing every hash. This is the
 *      [Next.js-recommended CSP pattern](https://nextjs.org/docs/app/guides/content-security-policy).
 *
 * Exit code: 0 always (informational).
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const RESULTS_DIR = join(import.meta.dir, "results");

const DEV_CSP = [
  "default-src 'self'",
  // Next.js dev mode (HMR, React Refresh, Turbopack) injects inline scripts
  // that need 'unsafe-inline'. Dev only — production uses nonces.
  "script-src 'self' 'unsafe-inline' 'unsafe-eval'",
  // Next.js, Tailwind 4, framer-motion, Radix UI inject inline styles.
  // style-src 'unsafe-inline' does not enable script execution.
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  // next/font self-hosts Google Fonts at /_next/static/media/
  "font-src 'self' data:",
  // No external API calls from the marketing site
  "connect-src 'self' ws: wss:",
  // Allow Next.js dev WebSocket for HMR (ws: is implicit in connect-src above)
  "media-src 'self' blob:",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
  "upgrade-insecure-requests",
].join("; ") + ";";

const PRODUCTION_CSP = [
  "default-src 'self'",
  // Production: per-request nonce generated by src/middleware.ts via
  // crypto.randomBytes(16). 'strict-dynamic' lets nonce-bearing scripts
  // (e.g. Next.js's own chunks) load their own deps without listing
  // every hash. No 'unsafe-inline' for scripts.
  "script-src 'self' 'nonce-{{NONCE}}' 'strict-dynamic'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  "connect-src 'self'",
  "media-src 'self' blob:",
  // No framing allowed — defeats clickjacking (strictly stronger than X-Frame-Options: DENY)
  "frame-ancestors 'none'",
  // No <base> injection — prevents relative URL redirection
  "base-uri 'self'",
  // Forms can only submit to same origin
  "form-action 'self'",
  // No Flash/Java/plugins (defense in depth — browsers already block these)
  "object-src 'none'",
  // Force HTTP→HTTPS upgrade
  "upgrade-insecure-requests",
].join("; ") + ";";

const PRODUCTION_CSP_RESOLVED = PRODUCTION_CSP.replace("'nonce-{{NONCE}}'", "'nonce-REPLACE_WITH_PER_REQUEST_NONCE'");

function main(): number {
  mkdirSync(RESULTS_DIR, { recursive: true });

  writeFileSync(join(RESULTS_DIR, "csp.txt"), DEV_CSP + "\n", "utf8");
  writeFileSync(join(RESULTS_DIR, "csp-production.txt"), PRODUCTION_CSP_RESOLVED + "\n", "utf8");

  console.log("═══════════════════════════════════════════════════════════");
  console.log(" RoyCSS Content Security Policy generator");
  console.log("═══════════════════════════════════════════════════════════");
  console.log("");
  console.log(" Development CSP (results/csp.txt):");
  console.log("   " + DEV_CSP);
  console.log("");
  console.log(" Production CSP (results/csp-production.txt):");
  console.log("   " + PRODUCTION_CSP_RESOLVED);
  console.log("");
  console.log(" Directives explained:");
  console.log("   default-src 'self'                — all resources from same origin by default");
  console.log("   script-src 'self' 'nonce-...'     — only nonce-bearing scripts execute (prod)");
  console.log("   script-src 'unsafe-inline'        — Next.js HMR requires this in dev only");
  console.log("   'strict-dynamic'                  — nonce scripts can load their own deps");
  console.log("   style-src 'self' 'unsafe-inline'  — Next.js/Tailwind inject inline styles");
  console.log("   img-src 'self' data: blob:        — local + data: SVG + blob: images");
  console.log("   font-src 'self' data:             — next/font self-hosts Google Fonts");
  console.log("   connect-src 'self'                — no external API calls");
  console.log("   frame-ancestors 'none'            — defeats clickjacking");
  console.log("   base-uri 'self'                   — no <base> injection");
  console.log("   form-action 'self'                — forms submit same origin only");
  console.log("   object-src 'none'                 — no plugins");
  console.log("   upgrade-insecure-requests         — force HTTPS");
  console.log("");
  console.log("═══════════════════════════════════════════════════════════");
  console.log(" ✅ CSPs written to results/csp.txt and results/csp-production.txt");
  console.log("═══════════════════════════════════════════════════════════");

  return 0;
}

try {
  process.exit(main());
} catch (err) {
  console.error("csp.ts: uncaught error:", err);
  process.exit(2);
}
