/**
 * Studio service — Prisma-backed Roy Studio visual-builder project store.
 *
 * Persisted via the Prisma `StudioProject` model. Seeds 4 studio
 * projects (each with a components tree) on first access. Starter
 * templates remain a static in-memory seed (no Prisma model).
 *
 * Field-mapping: the Prisma `StudioProject` model exposes (userId,
 * name, description, filesJson). The domain shape's `name`,
 * `description` map directly; the components tree is JSON-encoded
 * inside `filesJson`; (updatedAt, createdAt) are mirrored via the
 * Prisma `updatedAt`/`createdAt` columns.
 *
 * Note: the original seed used stable IDs (e.g. `studio-proj-landing-page`)
 * generated by `randomUUID()` *at module-load time* — we instead pin
 * the seed IDs to deterministic slugs so DB rows are stable across
 * server restarts.
 */
import { randomUUID } from "node:crypto";

import { CACHE_TTL } from "../../config/constants.js";
import { db } from "../../lib/db.js";
import { cache, cacheWrap } from "../../lib/cache.js";
import { createLogger } from "../../lib/logger.js";
import type {
  StudioComponent,
  StudioProject,
  StudioTemplate,
} from "../../types/index.js";
import { AppError } from "../../server/middleware/error.js";
import type {
  CreateStudioProjectInput,
  UpdateStudioProjectInput,
} from "./schema.js";

const log = createLogger("studio");

const PROJECTS_KEY = "studio:projects";
const detailKey = (id: string): string => `studio:project:${id}`;
const TEMPLATES_KEY = "studio:templates";

function invalidate(id?: string): void {
  cache.delete(PROJECTS_KEY);
  if (id) cache.delete(detailKey(id));
}

// ─── Seed: 4 studio projects with component trees ───────────────────────
// Pinned IDs (deterministic) so seedIfEmpty is idempotent across restarts.
function comp(
  type: string,
  props: Record<string, unknown> = {},
  children: StudioComponent[] = [],
): StudioComponent {
  return { id: `cmp-${randomUUID()}`, type, props, children };
}

const SEED_PROJECTS: StudioProject[] = [
  {
    id: "studio-proj-landing-page",
    name: "Landing Page",
    description: "Hero + feature grid + pricing + footer.",
    updatedAt: "2025-02-26T11:30:00.000Z",
    createdAt: "2025-02-20T09:00:00.000Z",
    components: [
      comp("Hero", { title: "Ship CSS faster", cta: "Get started" }, []),
      comp("FeatureGrid", { columns: 3 }, [
        comp("FeatureCard", { title: "Effects", icon: "sparkles" }, []),
        comp("FeatureCard", { title: "Themes", icon: "palette" }, []),
        comp("FeatureCard", { title: "Recipes", icon: "book" }, []),
      ]),
      comp("PricingTable", { tiers: ["starter", "pro", "team"] }, []),
      comp("Footer", {}, []),
    ],
  },
  {
    id: "studio-proj-dashboard",
    name: "Analytics Dashboard",
    description: "Sidebar + KPI cards + chart grid.",
    updatedAt: "2025-02-25T16:10:00.000Z",
    createdAt: "2025-02-18T14:00:00.000Z",
    components: [
      comp("Sidebar", { items: ["Overview", "Traffic", "Devices"] }, []),
      comp("MainContent", {}, [
        comp("KpiGrid", {}, [
          comp("KpiCard", { label: "Users", value: 48217 }, []),
          comp("KpiCard", { label: "API calls", value: 9_412_886 }, []),
          comp("KpiCard", { label: "Effects", value: 1284 }, []),
          comp("KpiCard", { label: "Avg ms", value: 87 }, []),
        ]),
        comp("ChartGrid", {}, [
          comp("LineChart", { metric: "Traffic" }, []),
          comp("BarChart", { metric: "Devices" }, []),
        ]),
      ]),
    ],
  },
  {
    id: "studio-proj-blog",
    name: "Engineering Blog",
    description: "Featured post + article list + tags.",
    updatedAt: "2025-02-24T10:00:00.000Z",
    createdAt: "2025-02-17T08:00:00.000Z",
    components: [
      comp("Header", { title: "Roy Engineering" }, []),
      comp("FeaturedPost", { title: "How we built RoyCSS", author: "Roy" }, []),
      comp("ArticleList", { limit: 10 }, [
        comp("ArticleCard", { title: "Container queries 101" }, []),
        comp("ArticleCard", { title: "OKLCH color migration" }, []),
        comp("ArticleCard", { title: "Animating with @starting-style" }, []),
      ]),
      comp("TagCloud", { tags: ["css", "performance", "a11y"] }, []),
    ],
  },
  {
    id: "studio-proj-docs",
    name: "Documentation Site",
    description: "TOC + content + code blocks.",
    updatedAt: "2025-02-23T13:30:00.000Z",
    createdAt: "2025-02-15T09:00:00.000Z",
    components: [
      comp("Sidebar", { items: ["Getting started", "Effects", "Recipes", "Patterns"] }, []),
      comp("MainContent", {}, [
        comp("Toc", {}, []),
        comp("Markdown", { source: "# Welcome to RoyCSS" }, []),
        comp("CodeBlock", { language: "tsx", code: "<Hero />" }, []),
      ]),
    ],
  },
];

// ─── Seed: 6 starter templates (static — no Prisma model) ──────────────
const SEED_TEMPLATES: StudioTemplate[] = [
  { id: "tpl-studio-blank", name: "Blank Canvas", category: "starter", description: "Empty project — start from scratch.", thumbnail: "https://cdn.roycss.dev/studio/blank.png", componentCount: 0 },
  { id: "tpl-studio-landing", name: "Landing Page", category: "marketing", description: "Hero + features + pricing + footer.", thumbnail: "https://cdn.roycss.dev/studio/landing.png", componentCount: 4 },
  { id: "tpl-studio-dashboard", name: "Dashboard", category: "app", description: "Sidebar + KPIs + chart grid.", thumbnail: "https://cdn.roycss.dev/studio/dashboard.png", componentCount: 3 },
  { id: "tpl-studio-docs", name: "Docs Site", category: "marketing", description: "TOC + content + code blocks.", thumbnail: "https://cdn.roycss.dev/studio/docs.png", componentCount: 3 },
  { id: "tpl-studio-portfolio", name: "Portfolio", category: "personal", description: "Gallery + about + contact.", thumbnail: "https://cdn.roycss.dev/studio/portfolio.png", componentCount: 4 },
  { id: "tpl-studio-blog", name: "Blog", category: "publishing", description: "Featured post + article list + tags.", thumbnail: "https://cdn.roycss.dev/studio/blog.png", componentCount: 3 },
];

interface ProjectWrapper {
  components: StudioComponent[];
  seedUpdatedAt: string;
  seedCreatedAt: string;
}

function toDbRow(p: StudioProject) {
  const wrapper: ProjectWrapper = {
    components: p.components,
    seedUpdatedAt: p.updatedAt,
    seedCreatedAt: p.createdAt,
  };
  return {
    id: p.id,
    userId: null,
    name: p.name,
    description: p.description,
    filesJson: JSON.stringify(wrapper),
  };
}

function toDomain(row: {
  id: string;
  name: string;
  description: string;
  filesJson: string;
  createdAt: Date;
  updatedAt: Date;
}): StudioProject {
  let wrapper: ProjectWrapper = {
    components: [],
    seedUpdatedAt: row.updatedAt.toISOString(),
    seedCreatedAt: row.createdAt.toISOString(),
  };
  try {
    wrapper = JSON.parse(row.filesJson) as ProjectWrapper;
  } catch {
    // Keep defaults.
  }
  return {
    id: row.id,
    name: row.name,
    description: row.description,
    components: wrapper.components,
    updatedAt: wrapper.seedUpdatedAt,
    createdAt: wrapper.seedCreatedAt,
  };
}

let seedPromise: Promise<void> | null = null;
async function seedIfEmpty(): Promise<void> {
  if (seedPromise) return seedPromise;
  seedPromise = (async () => {
    const count = await db.studioProject.count();
    if (count === 0) {
      await db.studioProject.createMany({
        data: SEED_PROJECTS.map(toDbRow),
      });
      log.info("Studio projects seeded", { count: SEED_PROJECTS.length });
    }
  })().catch((err) => {
    seedPromise = null;
    throw err;
  });
  return seedPromise;
}

/** List all studio projects. Cached. */
export async function listProjects(): Promise<StudioProject[]> {
  return cacheWrap(
    PROJECTS_KEY,
    async () => {
      await seedIfEmpty();
      const rows = await db.studioProject.findMany({
        orderBy: { createdAt: "asc" },
      });
      return rows.map(toDomain);
    },
    CACHE_TTL.studioProjects,
  );
}

/** Get a single studio project by id. Cached. Throws 404 if missing. */
export async function getProjectById(id: string): Promise<StudioProject> {
  return cacheWrap(
    detailKey(id),
    async () => {
      await seedIfEmpty();
      const row = await db.studioProject.findUnique({ where: { id } });
      if (!row) throw AppError.notFound(`Studio project '${id}' not found`);
      return toDomain(row);
    },
    CACHE_TTL.studioProjectDetail,
  );
}

/** Create a new studio project. Invalidates list cache. */
export async function createProject(
  input: CreateStudioProjectInput,
): Promise<StudioProject> {
  const now = new Date().toISOString();
  const project: StudioProject = {
    id: `studio-proj-${randomUUID()}`,
    name: input.name,
    description: input.description,
    components: input.components,
    updatedAt: now,
    createdAt: now,
  };
  await db.studioProject.create({ data: toDbRow(project) });
  invalidate(project.id);
  log.info("Studio project created", { id: project.id, name: project.name });
  return project;
}

/** Update an existing studio project (partial). Invalidates caches. */
export async function updateProject(
  id: string,
  input: UpdateStudioProjectInput,
): Promise<StudioProject> {
  await seedIfEmpty();
  const row = await db.studioProject.findUnique({ where: { id } });
  if (!row) throw AppError.notFound(`Studio project '${id}' not found`);
  let wrapper: ProjectWrapper;
  try {
    wrapper = JSON.parse(row.filesJson) as ProjectWrapper;
  } catch {
    wrapper = { components: [], seedUpdatedAt: row.updatedAt.toISOString(), seedCreatedAt: row.createdAt.toISOString() };
  }
  const updatedName = input.name ?? row.name;
  const updatedDescription = input.description ?? row.description;
  const updatedComponents = input.components ?? wrapper.components;
  const now = new Date().toISOString();
  const updatedWrapper: ProjectWrapper = {
    components: updatedComponents,
    seedUpdatedAt: now,
    seedCreatedAt: wrapper.seedCreatedAt,
  };
  await db.studioProject.update({
    where: { id },
    data: {
      name: updatedName,
      description: updatedDescription,
      filesJson: JSON.stringify(updatedWrapper),
    },
  });
  invalidate(id);
  log.info("Studio project updated", { id });
  return toDomain({
    ...row,
    name: updatedName,
    description: updatedDescription,
    filesJson: JSON.stringify(updatedWrapper),
    updatedAt: new Date(),
  });
}

/** Delete a studio project by id. Invalidates caches. */
export async function deleteProject(id: string): Promise<void> {
  await seedIfEmpty();
  const row = await db.studioProject.findUnique({ where: { id } });
  if (!row) throw AppError.notFound(`Studio project '${id}' not found`);
  await db.studioProject.delete({ where: { id } });
  invalidate(id);
  log.info("Studio project deleted", { id });
}

/** List all studio starter templates. Cached. */
export async function listTemplates(): Promise<StudioTemplate[]> {
  return cacheWrap(
    TEMPLATES_KEY,
    () => Promise.resolve(SEED_TEMPLATES.map((t) => ({ ...t }))),
    CACHE_TTL.studioTemplates,
  );
}

/** Number of projects in the store. Sync stub — real count is in DB. */
export function projectsCount(): number {
  return SEED_PROJECTS.length;
}

/** Test-only: reset to seed. */
export function _resetStudioForTest(): void {
  seedPromise = null;
  invalidate();
}
