import type { Metadata } from "next";
import { pageMeta } from "@/lib/seo";
import { EFFECT_COUNT_FORMATTED, FULL_CSS_MIN_GZ_KB } from "@/lib/site-stats";

export const metadata: Metadata = pageMeta({
  path: "/docs/guides/tree-shaking",
  title: "Tree Shaking — RoyCSS Docs",
  description: "CSS doesn't tree-shake — RoyCSS subsets explicitly instead: export hand-picked effects or categories with the CLI, and measure the result.",
});

export default function TreeShakingPage() {
  return (
    <>
      <h1>Tree Shaking</h1>
      <p className="text-lg text-muted-foreground">
        Let&apos;s be precise about what is possible: CSS files
        cannot be tree-shaken by bundlers the way JS modules can.
        RoyCSS ships one stylesheet — all{" "}
        {EFFECT_COUNT_FORMATTED} effects, ~{FULL_CSS_MIN_GZ_KB} KB
        gzipped minified — and subsetting is an explicit step you
        run when you need it. This guide shows the three honest
        options and how to verify the savings.
      </p>

      <h2 id="three-modes">The three options</h2>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`/* 1. Everything — one import, ~${FULL_CSS_MIN_GZ_KB} KB gzipped */
import "roycss/css/min";

/* 2. Curated critical subset — ~3.6 KB gzipped (above-the-fold effects) */
import "roycss/critical.css";

/* 3. Your own subset — export exactly what you use */
/*    (one CLI command, see below) */
$ npx roycss export btn-glow hover-push-up --out src/styles/roycss.css`}</code>
      </pre>

      <h2 id="per-category">Whole categories</h2>
      <p>
        If a bundle-of-everything is too heavy but you use a
        category heavily, export the whole category. Measured
        with the real CLI:
      </p>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`$ npx roycss export --category buttons --out roycss-buttons.css
✓ Exported 55 effects to roycss-buttons.css (27.2KB)
                                          (~3.7 KB gzipped)

$ npx roycss export --category hover --out roycss-hover.css
✓ Exported 120 effects to roycss-hover.css (55.8KB)
                                          (~8.7 KB gzipped)`}</code>
      </pre>

      <h2 id="per-effect">Hand-picked effects for landing pages</h2>
      <p>
        Marketing pages and microsites often need exactly two or
        three effects. A hand-picked export lands at hundreds of
        bytes gzipped:
      </p>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`$ npx roycss export btn-glow hover-push-up text-shimmer \\
    --out src/styles/roycss.css

✓ Exported 3 effects to src/styles/roycss.css (1.6KB)
                                            (~0.7 KB gzipped)

Effects:
  roycss-btn-glow        — Glow Button   (Button Effects)
  roycss-hover-push-up   — Push Up       (Hover Effects)
  roycss-text-shimmer    — Shimmer Text  (Text Effects)`}</code>
      </pre>
      <p>
        Tags work too — <code>--tag attention</code> pulls every
        effect tagged for drawing attention.
      </p>

      <h2 id="custom-bundle">How the export is built</h2>
      <p>
        The CLI writes a plain CSS file with a header, the selected
        effects&apos; full CSS, and nothing else — no shared
        variables file, no runtime, no build step. It prints the
        import line to use:
      </p>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`/* src/styles/roycss.css — generated */
/* RoyCSS Custom Export
 * Effects: 3
 * Categories: Button Effects, Hover Effects, Text Effects
 * Generated by: roycss export (CLI v2.0.0)
 */

/* Glow Button */
.roycss-btn-glow { … }
/* Push Up */
.roycss-hover-push-up { … }`}</code>
      </pre>

      <h2 id="bundler-config">Bundler notes</h2>
      <p>
        Whichever option you choose, the import is a single CSS
        file, so every bundler handles it natively:
      </p>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`// Vite / webpack 5 (css-loader) / Turbopack (Next.js) — all the same:
import "roycss/css/min";
import "./src/styles/roycss.css";   // your exported subset

/* or in CSS: */
@import "roycss/css/min";`}</code>
      </pre>

      <h2 id="verify">Verify what you actually use</h2>
      <p>
        Always measure. <code>roycss stats</code> scans your source
        for <code>roycss-*</code> usage and reports coverage;
        <code>roycss doctor</code> warns when your local{" "}
        <code>roycss.css</code> exceeds 1 MB and suggests an
        export:
      </p>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`$ npx roycss stats

Total usages: 14 across 6 unique effects in 12 source files
Catalog coverage: 6/1959 effects (0.3%)

Top 6 effects:
   1. roycss-btn-glow           ×4  — Glow Button
   2. roycss-hover-push-up      ×3  — Push Up
   ...`}</code>
      </pre>

      <h2 id="dont-over-optimize">Don&apos;t over-optimize</h2>
      <p>
        A subset is a maintenance liability: every new effect you
        adopt needs re-exporting. For apps under active
        development, the full stylesheet (or the critical subset +
        lazy-loaded full file) is the better default — save the
        export step for shipping a landing page or a
        size-budgeted widget.
      </p>
    </>
  );
}
