import type { Metadata } from "next";
import { pageMeta } from "@/lib/seo";
import { CATEGORY_COUNT, EFFECT_COUNT_FORMATTED } from "@/lib/site-stats";

export const metadata: Metadata = pageMeta({
  path: "/docs/guides/contributing",
  title: "Contributing — RoyCSS Docs",
  description: "How to contribute to RoyCSS: repo layout, effect conventions, PR checklist, and release process.",
});

export default function ContributingPage() {
  return (
    <>
      <h1>Contributing</h1>
      <p className="text-lg text-muted-foreground">
        RoyCSS is open source under the MIT license. This guide
        walks through the repo layout, contribution conventions,
        and the PR checklist that keeps the library consistent.
        The same content lives in{" "}
        <code>docs/CONTRIBUTING.md</code> in the repository — that
        file is the source of truth.
      </p>

      <h2 id="repo-layout">Repo layout</h2>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`roycss/
  src/
    lib/
      effects-batch-XX.ts  ← the catalog: 52 batch files,
                             one CSSEffect object per effect
      roycss-types.ts      ← the CSSEffect interface
      roycss-effects.ts    ← aggregates the batches (${EFFECT_COUNT_FORMATTED} effects)
      effect-taxonomy.ts   ← the ${CATEGORY_COUNT} category definitions
    app/                   ← the Next.js site (this docs site)
    cli/index.ts           ← the roycss CLI
  dist/                    ← generated by bun run build:package
  mcp-server/              ← the @roycss/mcp-server package
  perf/                    ← benchmark harness + budgets
  docs/                    ← governance docs (CONTRIBUTING, SEMVER…)
  backend-node/            ← the Express API
  tests/                   ← test suites`}</code>
      </pre>

      <h2 id="effect-conventions">Effect authoring conventions</h2>
      <ul className="list-disc pl-6 space-y-1">
        <li>Effects are <code>CSSEffect</code> objects in <code>src/lib/effects-batch-XX.ts</code> — add to the lowest-numbered batch with room, or register a new batch in <code>roycss-effects.ts</code>.</li>
        <li>Class prefix: every effect class starts with <code>roycss-</code>.</li>
        <li>Keyframes prefix: every <code>@keyframes</code> rule starts with <code>roy-</code>.</li>
        <li>Always include a <code>prefers-reduced-motion: reduce</code> guard.</li>
        <li>Use OKLCH colors — reference <code>src/lib/design-tokens.ts</code>; no indigo or blue as primary.</li>
        <li>GPU-accelerate: animate <code>transform</code> and <code>opacity</code> only, never <code>top</code>/<code>left</code>/<code>width</code>.</li>
      </ul>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`{
  id: "animations-float-card",
  name: "Floating Card",
  category: "animations",        // one of the ${CATEGORY_COUNT} in effect-taxonomy.ts
  description: "A card that gently floats up and down on hover.",
  cssCode: \`
    .roycss-animations-float-card {
      transition: transform 0.3s ease;
    }
    .roycss-animations-float-card:hover {
      animation: roy-float 1.5s ease-in-out infinite;
    }
    @keyframes roy-float {
      0%, 100% { transform: translateY(0); }
      50%      { transform: translateY(-6px); }
    }
    @media (prefers-reduced-motion: reduce) {
      .roycss-animations-float-card:hover { animation: none; }
    }
  \`,
  previewType: "box",
  tags: ["hover", "float", "card", "subtle"],
}`}</code>
      </pre>

      <h2 id="pr-checklist">PR checklist</h2>
      <p>
        Before opening a PR, verify:
      </p>
      <ul className="list-disc pl-6 space-y-1">
        <li><code>bun run lint</code> and <code>npx tsc --noEmit</code> pass.</li>
        <li>The effect follows the conventions above (prefixes, guard, OKLCH).</li>
        <li>Tested at three viewports — 375px, 768px, 1920px (mobile-first).</li>
        <li>Toggled <code>prefers-reduced-motion</code> and verified the static fallback.</li>
        <li>44px minimum touch targets and semantic HTML where the change touches UI.</li>
        <li>Screenshots/GIFs for visual changes, and the batch file you added to.</li>
      </ul>

      <h2 id="commit-style">Commit style</h2>
      <p>
        RoyCSS uses Conventional Commits — short, scoped, in the
        imperative mood:
      </p>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`feat(hover): add hover-wobble effect
fix(text): correct gradient-clip on Safari
docs(api): document the borders page sizing note
chore(build): bump lightningcss to 1.34`}</code>
      </pre>

      <h2 id="release-process">Release process</h2>
      <p>
        Releases use Changesets — version bumps and changelog
        entries are generated from changeset files merged in PRs:
      </p>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`# add a changeset describing your change (in the PR)
bun run changeset

# maintainer: version + build + publish (from package scripts)
bun run build:package      # regenerates dist/ from the catalog
bun run publish:validate   # pre-publish checks
npm publish`}</code>
      </pre>
      <p>
        The published <code>dist/</code> artifacts (roycss.css,
        effects.json, class-index.json, …) are all generated from
        the same catalog — which is why the site, the CLI, and
        the {EFFECT_COUNT_FORMATTED} classes can never drift apart.
      </p>

      <h2 id="cla">Contributor license</h2>
      <p>
        RoyCSS uses the standard MIT license with no CLA. By
        contributing, you agree your contributions are licensed
        under the project&apos;s MIT license.
      </p>

      <h2 id="communication">Communication</h2>
      <p>
        Discuss large changes in a GitHub issue before opening a
        PR. Smaller fixes (typos, single-effect adds, lint fixes)
        can go straight to a PR with no pre-discussion.
      </p>
    </>
  );
}
