import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contributing — RoyCSS Docs",
  description: "How to contribute to RoyCSS: repo layout, conventions, PR checklist, and release process.",
};

export default function ContributingPage() {
  return (
    <>
      <h1>Contributing</h1>
      <p className="text-lg text-muted-foreground">
        RoyCSS is open source under the MIT license. This guide
        walks through the repo layout, contribution conventions,
        and the PR checklist that keeps the library consistent.
      </p>

      <h2 id="repo-layout">Repo layout</h2>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`roycss/
  src/
    effects/        ← source CSS per effect, one file each
    roymotion/      ← JS-powered opt-in effects
    base.css         ← reset + variables
    effects.css      ← bundle entry (imports all categories)
  dist/             ← generated by \`bun run build\`
  scripts/          ← build helpers (palette gen, etc.)
  test/             ← visual regression snapshots
  docs/             ← this documentation
  CONTRIBUTING.md   ← this guide in raw form`}</code>
      </pre>

      <h2 id="effect-conventions">Effect authoring conventions</h2>
      <ul className="list-disc pl-6 space-y-1">
        <li>One effect per file, named <code>r-&lt;category&gt;-&lt;action&gt;.css</code>.</li>
        <li>Always start the file with a comment naming the effect and its purpose.</li>
        <li>Use RoyCSS variables — never hard-code colors or sizes.</li>
        <li>Always include a <code>prefers-reduced-motion</code> guard.</li>
        <li>Never use <code>!important</code>.</li>
      </ul>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`/* r-hover-wobble — playful 4deg wobble on hover */
.r-hover-wobble {
  transition: transform var(--r-duration, 180ms);
}
.r-hover-wobble:hover {
  animation: r-wobble 600ms ease-out;
}
@keyframes r-wobble {
  0%   { transform: rotate(0deg); }
  25%  { transform: rotate(-4deg); }
  75%  { transform: rotate(4deg); }
  100% { transform: rotate(0deg); }
}
@media (prefers-reduced-motion: reduce) {
  .r-hover-wobble:hover { animation: none; }
}`}</code>
      </pre>

      <h2 id="pr-checklist">PR checklist</h2>
      <p>
        Before opening a PR, verify:
      </p>
      <ul className="list-disc pl-6 space-y-1">
        <li>Effect file follows the conventions above.</li>
        <li>The effect is registered in <code>roycss.effects.json</code> (the linter catalog).</li>
        <li>The effect is added to the appropriate category entry in the sitemap.</li>
        <li>A visual regression snapshot is added under <code>test/snapshots/</code>.</li>
        <li><code>roycss inspect &lt;your-class&gt;</code> prints the right metadata.</li>
        <li>Lighthouse score on the demo page is ≥ 95.</li>
        <li>Contrast of any color-bearing variant passes AA.</li>
      </ul>

      <h2 id="commit-style">Commit style</h2>
      <p>
        RoyCSS uses Conventional Commits — short, scoped, in the
        imperative mood:
      </p>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`feat(hover): add r-hover-wobble
fix(text): correct gradient-clip on Safari
docs(api): document r-border-corners modifier
chore(build): bump lightningcss to 1.34`}</code>
      </pre>

      <h2 id="release-process">Release process</h2>
      <p>
        RoyCSS releases are cut from the <code>main</code> branch on
        a 2-week cadence. Maintainers run:
      </p>
      <pre className="bg-muted/50 rounded-lg p-4 overflow-x-auto text-sm">
        <code>{`# 1. Bump version
bun run scripts/bump-version.ts 2.1.0

# 2. Build + publish
bun run build
npm publish

# 3. CDN publish (auto, ~5 min)
# 4. Tag the release
git tag v2.1.0 && git push --tags`}</code>
      </pre>

      <h2 id="cla">Contributor license</h2>
      <p>
        RoyCSS uses the standard MIT license with no CLA. By
        contributing, you agree your contributions are licensed
        under the project’s MIT license.
      </p>

      <h2 id="communication">Communication</h2>
      <p>
        Discuss large changes in a GitHub issue before opening a
        PR. Smaller fixes (typos, single-effect adds, lint fixes)
        can go straight to a PR with no pre-discussion.
      </p>

      <h2 id="recognition">Recognition</h2>
      <p>
        All contributors are listed in the{" "}
        <a className="text-emerald-700 dark:text-emerald-300 hover:underline" href="https://github.com/Roy-Wanyoike/roycss">
          GitHub repository
        </a>{" "}
        and credited in the{" "}
        <a className="text-emerald-700 dark:text-emerald-300 hover:underline" href="/docs/guides/changelog">
          changelog
        </a>{" "}
        for the release that ships their first contribution.
      </p>
    </>
  );
}
