/**
 * Build script: generates the VSCode extension's embedded effects data.
 *
 * Outputs:
 *   vscode-extension/src/effects-data.ts  — compact metadata for all 1569 effects
 *                                            (id, name, category, description, tags, previewType).
 *                                            Embedded in the .vsix, <500 KB compiled.
 *   vscode-extension/data/css-data.json   — full cssCode map keyed by effect id.
 *                                            ~1.1 MB, lazy-loaded on hover/playground demand.
 *
 * Source of truth: /home/z/my-project/src/lib/roycss-effects.ts (all 34 batches).
 *
 * Usage:  bun run scripts/build-vscode-effects.ts
 */

import { effects } from "../src/lib/roycss-effects";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dir, "..", "vscode-extension");
const SRC_DIR = join(ROOT, "src");
const DATA_DIR = join(ROOT, "data");
mkdirSync(SRC_DIR, { recursive: true });
mkdirSync(DATA_DIR, { recursive: true });

console.log(`Building VSCode extension data from ${effects.length} effects...`);

// ───────────────────────────────────────────────────────────────────────
// 1. Validate the source data
// ───────────────────────────────────────────────────────────────────────

const seenIds = new Set<string>();
const errors: string[] = [];
for (const e of effects) {
  if (!e.id) errors.push(`Effect missing id: ${JSON.stringify(e).slice(0, 200)}`);
  if (seenIds.has(e.id)) errors.push(`Duplicate effect id: ${e.id}`);
  seenIds.add(e.id);
  if (!e.name) errors.push(`Effect ${e.id} missing name`);
  if (!e.description) errors.push(`Effect ${e.id} missing description`);
  if (!e.tags || e.tags.length === 0) errors.push(`Effect ${e.id} has no tags`);
  if (!e.cssCode) errors.push(`Effect ${e.id} missing cssCode`);
  if (!e.category) errors.push(`Effect ${e.id} missing category`);
  if (!e.previewType) errors.push(`Effect ${e.id} missing previewType`);
}
if (errors.length > 0) {
  console.error(`✗ Validation failed (${errors.length} errors). First 10:`);
  for (const err of errors.slice(0, 10)) console.error(`  - ${err}`);
  process.exit(1);
}
console.log(`  ✓ All ${effects.length} effects validated (no duplicates, no missing fields)`);

// ───────────────────────────────────────────────────────────────────────
// 2. Generate src/effects-data.ts (compact metadata, embedded in .vsix)
// ───────────────────────────────────────────────────────────────────────

interface EffectMeta {
  id: string;
  name: string;
  category: string;
  description: string;
  tags: string[];
  previewType: string;
  /** Number of <span> children for loaders etc. */
  childCount?: number;
  /** Optional preview text for text/button previews. */
  previewText?: string;
}

const metadata: EffectMeta[] = effects.map((e) => ({
  id: e.id,
  name: e.name,
  category: e.category,
  description: e.description,
  tags: e.tags,
  previewType: e.previewType,
  childCount: e.childCount,
  previewText: e.previewText,
}));

const tsHeader = `/**
 * RoyCSS VSCode Extension — embedded effect metadata.
 *
 * AUTO-GENERATED by scripts/build-vscode-effects.ts. Do not edit by hand.
 * Source: /home/z/my-project/src/lib/roycss-effects.ts (all 34 batches)
 *
 * Stats:
 *   - Effects: ${metadata.length}
 *   - Categories: ${new Set(metadata.map((m) => m.category)).size}
 *   - Compiled size: ~${(JSON.stringify(metadata).length / 1024).toFixed(0)} KB
 *
 * Full cssCode for each effect is loaded lazily from ../data/css-data.json
 * (see getCssCode below). That file is ~1.1 MB and is only read when the
 * user hovers over a roycss-* token or opens the playground webview.
 */

export interface EffectMeta {
  id: string;
  name: string;
  category: string;
  description: string;
  tags: string[];
  previewType: string;
  childCount?: number;
  previewText?: string;
}

`;

const tsBody = `export const effects: EffectMeta[] = ${JSON.stringify(metadata)};

// ───────────────────────────────────────────────────────────────────────
// Lookups (built once at module load)
// ───────────────────────────────────────────────────────────────────────

const byId = new Map<string, EffectMeta>(effects.map((e) => [e.id, e]));

const byClass = new Map<string, EffectMeta>(
  effects.map((e) => [\`roycss-\${e.id}\`, e]),
);

export function findById(id: string): EffectMeta | undefined {
  return byId.get(id);
}

export function findByClassName(className: string): EffectMeta | undefined {
  return byClass.get(className);
}

/**
 * All category labels present in the catalog, in stable order.
 */
export const categories: string[] = Array.from(
  new Set(effects.map((e) => e.category)),
).sort();

// ───────────────────────────────────────────────────────────────────────
// Lazy CSS loader
// ───────────────────────────────────────────────────────────────────────

import { readFileSync } from "fs";
import { join } from "path";

let cssCache: Record<string, string> | null = null;

function loadCssData(): Record<string, string> {
  if (cssCache) return cssCache;
  // __dirname at runtime is <extension-root>/out/src/
  // (we compile with rootDir="." so src/ is preserved as out/src/)
  // The css-data.json lives at <extension-root>/data/css-data.json
  // → go up two levels from out/src/ to reach <extension-root>/,
  //   then into data/.
  const dataPath = join(__dirname, "..", "..", "data", "css-data.json");
  try {
    const raw = readFileSync(dataPath, "utf-8");
    cssCache = JSON.parse(raw) as Record<string, string>;
  } catch (err) {
    // Best-effort: log and return empty map. The hover/playground will
    // degrade gracefully (no CSS preview, just metadata).
    console.error("[RoyCSS] Failed to load css-data.json:", err);
    cssCache = {};
  }
  return cssCache;
}

/**
 * Returns the full CSS source for the given effect id, or undefined if the
 * id is unknown. The css-data.json file is loaded lazily on first call and
 * cached for the extension lifetime.
 */
export function getCssCode(id: string): string | undefined {
  return loadCssData()[id];
}
`;

writeFileSync(join(SRC_DIR, "effects-data.ts"), tsHeader + tsBody, "utf-8");
const metaSize = Buffer.byteLength(tsHeader + tsBody, "utf-8");
console.log(
  `  ✓ src/effects-data.ts (${(metaSize / 1024).toFixed(1)} KB, ${metadata.length} effects)`,
);

// ───────────────────────────────────────────────────────────────────────
// 3. Generate data/css-data.json (full cssCode map, lazy-loaded)
// ───────────────────────────────────────────────────────────────────────

const cssMap: Record<string, string> = {};
for (const e of effects) {
  cssMap[e.id] = e.cssCode;
}

writeFileSync(join(DATA_DIR, "css-data.json"), JSON.stringify(cssMap), "utf-8");
const cssSize = Buffer.byteLength(JSON.stringify(cssMap), "utf-8");
console.log(`  ✓ data/css-data.json (${(cssSize / 1024).toFixed(1)} KB, ${Object.keys(cssMap).length} entries)`);

// ───────────────────────────────────────────────────────────────────────
// 4. Summary
// ───────────────────────────────────────────────────────────────────────

const categoryCounts = new Map<string, number>();
for (const m of metadata) {
  categoryCounts.set(m.category, (categoryCounts.get(m.category) || 0) + 1);
}

console.log("");
console.log(`✅ VSCode extension data built:`);
console.log(`   ${metadata.length} effects across ${categoryCounts.size} categories`);
console.log(`   effects-data.ts: ${(metaSize / 1024).toFixed(1)} KB (target: <500 KB ${metaSize < 500 * 1024 ? "✓" : "✗"})`);
console.log(`   css-data.json:   ${(cssSize / 1024).toFixed(1)} KB`);
console.log("");
console.log("   Category distribution:");
const sortedCats = Array.from(categoryCounts.entries()).sort((a, b) => b[1] - a[1]);
for (const [cat, count] of sortedCats) {
  console.log(`     ${cat.padEnd(20)} ${count}`);
}
