/**
 * Generate src/app/effects/_lib/effect-id-set.ts — the compact effect-id
 * authority for the proxy's router-level 404 (ISR hard-404 guarantee).
 *
 * Source of truth: the same catalog the pages use (src/lib/roycss-effects).
 * Drift is guarded by tests/unit/proxy-effect-404.test.ts, which fails if
 * the generated set diverges from the live catalog.
 *
 * Run: bunx tsx scripts/generate-effect-id-set.ts
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { effects } from "../src/lib/roycss-effects";

const here = dirname(fileURLToPath(import.meta.url));

const ids = effects.map((e) => e.id);
if (ids.length < 1000) {
  throw new Error(`catalog looks wrong: only ${ids.length} effects`);
}
const unique = new Set(ids);
if (unique.size !== ids.length) {
  throw new Error("duplicate effect ids in catalog");
}

const out = `// AUTO-GENERATED by scripts/generate-effect-id-set.ts — DO NOT EDIT BY HAND.
// Regenerate after catalog changes: bunx tsx scripts/generate-effect-id-set.ts
// Drift guard: tests/unit/proxy-effect-404.test.ts pins this to the catalog.
//
// Purpose: the compact id authority for the router-level 404 in src/proxy.ts.
// Kept SEPARATE from src/lib/roycss-effects so the proxy (which bundles this
// file) does not pull the ~2MB CSS catalog into the middleware bundle.
// ${unique.size} ids, ~${Math.round(JSON.stringify([...unique]).length / 1024)}KB.

export const EFFECT_ID_COUNT = ${unique.size};

/** Every valid /effects/<id> slug — single source: the catalog. */
export const effectIdSet: ReadonlySet<string> = new Set(${JSON.stringify([...unique])});

/**
 * Router-level 404 decision for the proxy (ISR hard-404 guarantee).
 *
 * With ISR-on-demand rendering (dynamicParams = true), the page-level
 * notFound() renders INSIDE the streamed response — the prerendered app
 * shell may already have flushed with HTTP 200 (soft-404). The proxy runs
 * BEFORE routing/streaming, so rejecting here restores the hard 404 the
 * pre-ISR build (dynamicParams = false) guaranteed at the router level.
 *
 * Only single-segment /effects/<slug> paths are validated: the bare
 * /effects listing, query strings, and deeper subpaths are not effect
 * detail pages and pass through untouched.
 */
export function isUnknownEffectPath(pathname: string): boolean {
  if (!pathname.startsWith("/effects/")) return false;
  const slug = pathname.slice("/effects/".length);
  if (slug === "" || slug.includes("/")) return false;
  return !effectIdSet.has(slug);
}
`;

writeFileSync(resolve(here, "../src/app/effects/_lib/effect-id-set.ts"), out);
console.log(`wrote ${unique.size} effect ids`);
