// src/proxy.ts (Next.js 16 middleware — "proxy" per the middleware→proxy rename)
//
// Applies a STATIC-SAFE production Content-Security-Policy to every response.
//
// ⚠️ READ THIS BEFORE TOUCHING THE CSP — HISTORY REPEATS ITSELF ⚠️
//
// DO NOT reintroduce per-request nonces or 'strict-dynamic'. That approach was
// tried twice and took the production site down both times:
//
//   - Issue #35 ("CSP too strict") first introduced a nonce-based CSP.
//   - Issue #54 (P0 production outage, this fix): the nonce policy served by
//     this proxy (`script-src 'self' 'nonce-<random>' 'strict-dynamic'`) made
//     https://roycss.vercel.app serve full prerendered HTML while the browser
//     executed ZERO scripts — the site was stuck on "Loading RoyCSS…" forever
//     (`self.__next_f` was undefined; no hydration, no streaming swap).
//
// WHY nonce + 'strict-dynamic' can NEVER work here (fundamental, not a bug
// we can patch around):
//
//   1. 'strict-dynamic' tells the browser to IGNORE host-source allowlists
//      (like 'self') — only scripts carrying the exact per-request nonce (or
//      scripts injected by an already-trusted nonced script) may run.
//   2. Statically PRERENDERED pages (e.g. docs pages, and any page Next.js
//      prerenders at build time — on older deployments `/` itself) have their
//      <script> tags BAKED INTO THE HTML AT BUILD TIME. The build happens
//      once; the nonce is generated per request. A build-time script tag can
//      therefore never carry a matching per-request nonce → blocked.
//   3. React 19 streaming emits UNNONCED inline scripts (the `$RC(...)` swap
//      functions that reveal streamed server-rendered content, plus the
//      `self.__next_f.push(...)` flight-data bootstrap scripts). They are
//      generated by the framework and cannot be nonced by application code →
//      blocked → streamed content stays hidden behind the loading fallback.
//
// The result: HTML arrives, CSP blocks every script, and the page never
// hydrates. This failure is SILENT for any statically prerendered route — a
// page can be dynamic today, get prerendered by a future refactor, and break
// in production the moment it ships. That is exactly how #54 happened.
//
// THE ACCEPTED TRADEOFF (deliberate, reviewed, documented):
//
//   - `script-src 'self' 'unsafe-inline'` — 'unsafe-inline' for scripts is the
//     pragmatic, industry-standard tradeoff for Next.js App Router apps that
//     serve prerendered/static pages. Without it, framework-generated inline
//     scripts (React streaming `$RC`, `__next_f` bootstrap) are unexecuted and
//     the site is dead. Mitigations that stay in place: object-src 'none'
//     (no plugins), base-uri 'self' (no <base> hijack), frame-ancestors
//     'none' (no clickjacking), form-action 'self' (no form exfil), and
//     connect-src 'self' (inline script can't phone home to third parties).
//     Revisit ONLY with a hash-based CSP for the known inline scripts —
//     per-request nonces are permanently off the table for this app.
//   - `connect-src 'self'` — safe and intentionally tight: the frontend never
//     calls the Express backend cross-origin. All backend traffic goes
//     SAME-ORIGIN through the /api/v1/[...path] route handler proxy in
//     src/app/api/v1/, so the browser only ever sees same-origin fetches.
//
// See:
//   - Issue #54 (the P0 outage this policy fixes) and issue #35 (the earlier,
//     ineffective nonce "fix" whose approach caused the outage)
//   - security/CSP.md, security/results/csp-production.txt
//   - Next.js CSP guide: https://nextjs.org/docs/app/guides/content-security-policy
//     (its nonce guidance assumes fully dynamic rendering — not our case)

import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";
import { isUnknownEffectPath } from "./app/effects/_lib/effect-id-set";

/**
 * Build the production CSP.
 *
 * Static-safe: no nonce, no 'strict-dynamic' (see the header comment for why
 * those are permanently banned here). Every directive is a plain host-source
 * allowlist so the policy is identical for dynamically rendered AND build-time
 * prerendered responses — the browser validates the same HTML either way.
 */
function buildProductionCsp(): string {
  return (
    [
      "default-src 'self'",
      // 'unsafe-inline' is required for React streaming ($RC swaps) and the
      // __next_f bootstrap scripts on prerendered pages — see header comment.
      "script-src 'self' 'unsafe-inline'",
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data: blob:",
      "font-src 'self' data:",
      // Backend calls are same-origin via /api/v1 proxy — no cross-origin
      // connects are needed, so this stays locked to 'self'.
      "connect-src 'self'",
      "media-src 'self' blob:",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "object-src 'none'",
      "upgrade-insecure-requests",
    ].join("; ") + ";"
  );
}

/**
 * Minimal branded hard-404 body for unknown /effects/<id> slugs.
 *
 * Served directly by the proxy (router level) because ISR-on-demand
 * rendering streams the app shell with HTTP 200 before the page's
 * notFound() can throw — see effect-id-set.ts for the full rationale.
 * A real 404 status with a small, brand-consistent body keeps the UX
 * acceptable for junk URLs while preserving the SEO contract.
 */
function unknownEffect404(): NextResponse {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>Effect not found — RoyCSS</title>
<style>
body{margin:0;min-height:100vh;display:grid;place-items:center;background:#0a0a0a;color:#fafafa;font-family:system-ui,sans-serif}
.card{text-align:center;padding:2rem}
h1{font-size:1.5rem;margin:0 0 .5rem}
p{color:#a1a1aa;margin:0 0 1.5rem}
a{color:#10b981;text-decoration:none;font-weight:600}
a:hover{text-decoration:underline}
</style>
</head>
<body><div class="card">
<h1>Effect not found</h1>
<p>The effect you're looking for doesn't exist in the RoyCSS catalog.</p>
<a href="/effects">Browse all effects</a>
</div></body>
</html>`;
  return new NextResponse(html, {
    status: 404,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "public, max-age=300, s-maxage=3600",
      // Issue #192: this proxy-crafted response bypasses next.config.ts
      // headers() — carry the anti-framing + transport-security headers
      // here too so the security copy's "every response" claim holds.
      "X-Frame-Options": "DENY",
      "Strict-Transport-Security":
        "max-age=63072000; includeSubDomains; preload",
    },
  });
}

export function proxy(request: NextRequest): NextResponse {
  // Router-level hard 404 for unknown effect slugs (ISR guarantee — see
  // effect-id-set.ts). Runs BEFORE routing/streaming so the status is a
  // real 404, identical to the pre-ISR dynamicParams=false behavior.
  if (isUnknownEffectPath(request.nextUrl.pathname)) {
    return unknownEffect404();
  }

  // In dev, do nothing — the dev CSP from next.config.ts applies.
  // Next.js sets NODE_ENV based on the script: `next dev` → "development",
  // `next build && next start` → "production".
  if (process.env.NODE_ENV !== "production") {
    return NextResponse.next();
  }

  // Apply the static-safe CSP to the response. This overrides the looser
  // CSP set by next.config.ts `headers()` (which mainly exists for dev).
  // Applied on EVERY response for every route the matcher below matches,
  // including prerendered pages served from the static cache.
  const response = NextResponse.next();
  response.headers.set("Content-Security-Policy", buildProductionCsp());
  return response;
}

export const config = {
  // Run middleware on every route except static assets and Next.js internals.
  matcher: [
    /*
     * Match all request paths except:
     * - /_next/static (static files)
     * - /_next/image (image optimization)
     * - /_next/media (next/font self-hosted fonts)
     * - /favicon.ico, /apple-icon.png, /logo.svg, etc. (public assets)
     * - /roycss-source.zip, /RoyCSS.zip (public downloadables)
     */
    "/((?!_next/static|_next/image|_next/media|favicon\\.png|apple-icon\\.png|logo\\.svg|roycss-logo-.*|RoyCSS\\.zip|roycss-source\\.zip|images/|robots\\.txt).*)",
  ],
};
