/**
 * Inline copy of the EffectCategory union from
 * `/home/z/my-project/src/lib/roycss-types.ts`. Inlined (not imported) so
 * the inspector directory is self-contained for typecheck purposes — the
 * parent project's tsconfig has a different rootDir.
 *
 * If the upstream EffectCategory grows, this union must be updated and
 * `scripts/extract-top-effects.ts` re-run. The build will fail typecheck if
 * the embedded JSON contains a category not in this union.
 */
export type EffectCategory =
  | "animations"
  | "hover"
  | "text"
  | "backgrounds"
  | "loaders"
  | "3d-transforms"
  | "buttons"
  | "cards"
  | "borders"
  | "filters"
  | "forms"
  | "navigation"
  | "scroll"
  | "cursor"
  | "page-transitions"
  | "glass-ui"
  | "particles"
  | "microinteractions"
  | "visual"
  | "misc";

import data from "./effects-data.json";

/**
 * Embedded effect metadata for the Inspector extension.
 *
 * Source: top 100 effects from `/home/z/my-project/src/lib/roycss-effects.ts`,
 * regenerated by `scripts/extract-top-effects.ts`. Total size <50KB to keep
 * the extension bundle lightweight (see docs/benchmarks).
 *
 * Why a Map: O(1) lookup by effect id from the content script + side panel.
 * Why not the full 1569: the Inspector only needs the top 100 for offline
 * detail view; effects outside the top 100 fall back to a "View on RoyCSS"
 * link in the side panel.
 */

export interface InspectorEffect {
  id: string;
  name: string;
  category: EffectCategory;
  description: string;
  tags: string[];
  cssCode: string;
}

const effectsList = data as unknown as InspectorEffect[];

/** Map of effect id → InspectorEffect, for O(1) lookup. */
export const effectsData: Map<string, InspectorEffect> = new Map(
  effectsList.map((e) => [e.id, e]),
);

/** Ordered list (same order as the source library — most recently curated first). */
export { effectsList };

/** Total embedded effect count. */
export const EFFECT_COUNT: number = effectsList.length;
