/**
 * Proxy router-level 404 contract for /effects/<id> (ISR hard-404 guarantee).
 *
 * Background: /effects/[id] renders ISR-on-demand (dynamicParams = true —
 * the deployment-size fix). The page's notFound() renders INSIDE the
 * streamed response, so the prerendered app shell may flush with HTTP 200
 * first (soft-404). src/proxy.ts therefore rejects unknown slugs BEFORE
 * routing via isUnknownEffectPath() — restoring the hard router-level 404
 * that dynamicParams = false used to guarantee.
 *
 * This suite pins:
 *   1. The generated id set matches the live catalog exactly (drift guard —
 *      regenerate with: bunx tsx scripts/generate-effect-id-set.ts).
 *   2. The path-classification contract (what the proxy 404s and passes).
 */
import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { effects } from "@/lib/roycss-effects";
import { effectIdSet, EFFECT_ID_COUNT, isUnknownEffectPath } from "@/app/effects/_lib/effect-id-set";

describe("effect-id-set — catalog drift guard", () => {
  it("contains exactly the catalog's effect ids (count + membership)", () => {
    expect(EFFECT_ID_COUNT).toBe(effects.length);
    expect(effectIdSet.size).toBe(effects.length);
    for (const e of effects) {
      expect(effectIdSet.has(e.id)).toBe(true);
    }
  });

  it("is byte-derived from the generator (not hand-edited)", () => {
    const generated = readFileSync(
      resolve(__dirname, "../../src/app/effects/_lib/effect-id-set.ts"),
      "utf8",
    );
    expect(generated).toContain("AUTO-GENERATED by scripts/generate-effect-id-set.ts");
  });

  it("is compact enough for the proxy bundle (< 100 KB source)", () => {
    const size = readFileSync(
      resolve(__dirname, "../../src/app/effects/_lib/effect-id-set.ts"),
    ).byteLength;
    expect(size).toBeLessThan(100 * 1024);
  });
});

describe("isUnknownEffectPath — proxy 404 classification", () => {
  it("404s unknown single-segment effect slugs", () => {
    expect(isUnknownEffectPath("/effects/nonexistent-xyz")).toBe(true);
    expect(isUnknownEffectPath("/effects/totally-fresh-junk")).toBe(true);
  });

  it("passes real catalog ids", () => {
    expect(isUnknownEffectPath("/effects/pulse-glow")).toBe(false);
    expect(isUnknownEffectPath(`/effects/${effects[0]!.id}`)).toBe(false);
    expect(isUnknownEffectPath(`/effects/${effects[effects.length - 1]!.id}`)).toBe(false);
  });

  it("passes the listing and non-effect paths (no over-blocking)", () => {
    expect(isUnknownEffectPath("/effects")).toBe(false);
    expect(isUnknownEffectPath("/effects/")).toBe(false);
    expect(isUnknownEffectPath("/")).toBe(false);
    expect(isUnknownEffectPath("/docs/getting-started")).toBe(false);
    expect(isUnknownEffectPath("/api/og?effect=pulse-glow")).toBe(false);
  });

  it("passes deeper subpaths (not effect detail pages)", () => {
    // A trailing slash or nested segment is not a detail-page slug; the
    // router handles those (and the page's own notFound() covers them).
    expect(isUnknownEffectPath("/effects/junk/sub")).toBe(false);
    expect(isUnknownEffectPath("/effects/junk/")).toBe(false);
  });
});
